project_name: terraform-import-script

builds:
  - main: ./import/import.go
    binary: terraform-import-script
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs:
  - cmd: gpg
    args:
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
    artifacts: checksum

# Customize the release name to differentiate it from your main project releases
release:
  name_template: "Terraform Import Script {{.Tag}}"
  header: |
    # Terraform Import Script Release {{.Tag}}
    
    This release contains the Terraform import script, a standalone tool for importing resources into Terraform.