name: Terraform Provider Astro Issue
description: Create an issue for the Terraform Provider Astro.
labels: ["team/cp-applications", "team/cp-applications/be"]
projects: ["astronomer/113"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Provide context that gives your future self and others enough information to pick up this issue.
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: What needs to happen for this issue to be completed. These should be testable.
      placeholder: |
        - [] Add AC's here.
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? PRD? Notes? Logs? Slack Messages/Threads?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
