// Package labs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package labs

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	JWTScopes = "JWT.Scopes"
)

// Defines values for AlertEntityType.
const (
	AlertEntityTypeDEPLOYMENT AlertEntityType = "DEPLOYMENT"
)

// Defines values for AlertSeverity.
const (
	AlertSeverityCRITICAL AlertSeverity = "CRITICAL"
	AlertSeverityINFO     AlertSeverity = "INFO"
	AlertSeverityWARNING  AlertSeverity = "WARNING"
)

// Defines values for AlertType.
const (
	AlertTypeDAGDURATION   AlertType = "DAG_DURATION"
	AlertTypeDAGFAILURE    AlertType = "DAG_FAILURE"
	AlertTypeDAGSUCCESS    AlertType = "DAG_SUCCESS"
	AlertTypeDAGTIMELINESS AlertType = "DAG_TIMELINESS"
	AlertTypeTASKDURATION  AlertType = "TASK_DURATION"
	AlertTypeTASKFAILURE   AlertType = "TASK_FAILURE"
)

// Defines values for AlertNotificationChannelEntityType.
const (
	AlertNotificationChannelEntityTypeDEPLOYMENT   AlertNotificationChannelEntityType = "DEPLOYMENT"
	AlertNotificationChannelEntityTypeORGANIZATION AlertNotificationChannelEntityType = "ORGANIZATION"
	AlertNotificationChannelEntityTypeWORKSPACE    AlertNotificationChannelEntityType = "WORKSPACE"
)

// Defines values for AlertNotificationChannelType.
const (
	DAGTRIGGER AlertNotificationChannelType = "DAG_TRIGGER"
	EMAIL      AlertNotificationChannelType = "EMAIL"
	OPSGENIE   AlertNotificationChannelType = "OPSGENIE"
	PAGERDUTY  AlertNotificationChannelType = "PAGERDUTY"
	SLACK      AlertNotificationChannelType = "SLACK"
)

// Defines values for BasicSubjectProfileSubjectType.
const (
	SERVICEKEY BasicSubjectProfileSubjectType = "SERVICEKEY"
	USER       BasicSubjectProfileSubjectType = "USER"
)

// Defines values for CreateDagDurationAlertRequestEntityType.
const (
	CreateDagDurationAlertRequestEntityTypeDEPLOYMENT CreateDagDurationAlertRequestEntityType = "DEPLOYMENT"
)

// Defines values for CreateDagDurationAlertRequestSeverity.
const (
	CreateDagDurationAlertRequestSeverityCRITICAL CreateDagDurationAlertRequestSeverity = "CRITICAL"
	CreateDagDurationAlertRequestSeverityINFO     CreateDagDurationAlertRequestSeverity = "INFO"
	CreateDagDurationAlertRequestSeverityWARNING  CreateDagDurationAlertRequestSeverity = "WARNING"
)

// Defines values for CreateDagDurationAlertRequestType.
const (
	CreateDagDurationAlertRequestTypeDAGDURATION   CreateDagDurationAlertRequestType = "DAG_DURATION"
	CreateDagDurationAlertRequestTypeDAGFAILURE    CreateDagDurationAlertRequestType = "DAG_FAILURE"
	CreateDagDurationAlertRequestTypeDAGSUCCESS    CreateDagDurationAlertRequestType = "DAG_SUCCESS"
	CreateDagDurationAlertRequestTypeDAGTIMELINESS CreateDagDurationAlertRequestType = "DAG_TIMELINESS"
	CreateDagDurationAlertRequestTypeTASKDURATION  CreateDagDurationAlertRequestType = "TASK_DURATION"
	CreateDagDurationAlertRequestTypeTASKFAILURE   CreateDagDurationAlertRequestType = "TASK_FAILURE"
)

// Defines values for CreateDagFailureAlertRequestEntityType.
const (
	CreateDagFailureAlertRequestEntityTypeDEPLOYMENT CreateDagFailureAlertRequestEntityType = "DEPLOYMENT"
)

// Defines values for CreateDagFailureAlertRequestSeverity.
const (
	CreateDagFailureAlertRequestSeverityCRITICAL CreateDagFailureAlertRequestSeverity = "CRITICAL"
	CreateDagFailureAlertRequestSeverityINFO     CreateDagFailureAlertRequestSeverity = "INFO"
	CreateDagFailureAlertRequestSeverityWARNING  CreateDagFailureAlertRequestSeverity = "WARNING"
)

// Defines values for CreateDagFailureAlertRequestType.
const (
	CreateDagFailureAlertRequestTypeDAGDURATION   CreateDagFailureAlertRequestType = "DAG_DURATION"
	CreateDagFailureAlertRequestTypeDAGFAILURE    CreateDagFailureAlertRequestType = "DAG_FAILURE"
	CreateDagFailureAlertRequestTypeDAGSUCCESS    CreateDagFailureAlertRequestType = "DAG_SUCCESS"
	CreateDagFailureAlertRequestTypeDAGTIMELINESS CreateDagFailureAlertRequestType = "DAG_TIMELINESS"
	CreateDagFailureAlertRequestTypeTASKDURATION  CreateDagFailureAlertRequestType = "TASK_DURATION"
	CreateDagFailureAlertRequestTypeTASKFAILURE   CreateDagFailureAlertRequestType = "TASK_FAILURE"
)

// Defines values for CreateDagSuccessAlertRequestEntityType.
const (
	CreateDagSuccessAlertRequestEntityTypeDEPLOYMENT CreateDagSuccessAlertRequestEntityType = "DEPLOYMENT"
)

// Defines values for CreateDagSuccessAlertRequestSeverity.
const (
	CreateDagSuccessAlertRequestSeverityCRITICAL CreateDagSuccessAlertRequestSeverity = "CRITICAL"
	CreateDagSuccessAlertRequestSeverityINFO     CreateDagSuccessAlertRequestSeverity = "INFO"
	CreateDagSuccessAlertRequestSeverityWARNING  CreateDagSuccessAlertRequestSeverity = "WARNING"
)

// Defines values for CreateDagSuccessAlertRequestType.
const (
	CreateDagSuccessAlertRequestTypeDAGDURATION   CreateDagSuccessAlertRequestType = "DAG_DURATION"
	CreateDagSuccessAlertRequestTypeDAGFAILURE    CreateDagSuccessAlertRequestType = "DAG_FAILURE"
	CreateDagSuccessAlertRequestTypeDAGSUCCESS    CreateDagSuccessAlertRequestType = "DAG_SUCCESS"
	CreateDagSuccessAlertRequestTypeDAGTIMELINESS CreateDagSuccessAlertRequestType = "DAG_TIMELINESS"
	CreateDagSuccessAlertRequestTypeTASKDURATION  CreateDagSuccessAlertRequestType = "TASK_DURATION"
	CreateDagSuccessAlertRequestTypeTASKFAILURE   CreateDagSuccessAlertRequestType = "TASK_FAILURE"
)

// Defines values for CreateDagTimelinessAlertRequestEntityType.
const (
	CreateDagTimelinessAlertRequestEntityTypeDEPLOYMENT CreateDagTimelinessAlertRequestEntityType = "DEPLOYMENT"
)

// Defines values for CreateDagTimelinessAlertRequestSeverity.
const (
	CreateDagTimelinessAlertRequestSeverityCRITICAL CreateDagTimelinessAlertRequestSeverity = "CRITICAL"
	CreateDagTimelinessAlertRequestSeverityINFO     CreateDagTimelinessAlertRequestSeverity = "INFO"
	CreateDagTimelinessAlertRequestSeverityWARNING  CreateDagTimelinessAlertRequestSeverity = "WARNING"
)

// Defines values for CreateDagTimelinessAlertRequestType.
const (
	CreateDagTimelinessAlertRequestTypeDAGDURATION   CreateDagTimelinessAlertRequestType = "DAG_DURATION"
	CreateDagTimelinessAlertRequestTypeDAGFAILURE    CreateDagTimelinessAlertRequestType = "DAG_FAILURE"
	CreateDagTimelinessAlertRequestTypeDAGSUCCESS    CreateDagTimelinessAlertRequestType = "DAG_SUCCESS"
	CreateDagTimelinessAlertRequestTypeDAGTIMELINESS CreateDagTimelinessAlertRequestType = "DAG_TIMELINESS"
	CreateDagTimelinessAlertRequestTypeTASKDURATION  CreateDagTimelinessAlertRequestType = "TASK_DURATION"
	CreateDagTimelinessAlertRequestTypeTASKFAILURE   CreateDagTimelinessAlertRequestType = "TASK_FAILURE"
)

// Defines values for CreateTaskDurationAlertRequestEntityType.
const (
	CreateTaskDurationAlertRequestEntityTypeDEPLOYMENT CreateTaskDurationAlertRequestEntityType = "DEPLOYMENT"
)

// Defines values for CreateTaskDurationAlertRequestSeverity.
const (
	CreateTaskDurationAlertRequestSeverityCRITICAL CreateTaskDurationAlertRequestSeverity = "CRITICAL"
	CreateTaskDurationAlertRequestSeverityINFO     CreateTaskDurationAlertRequestSeverity = "INFO"
	CreateTaskDurationAlertRequestSeverityWARNING  CreateTaskDurationAlertRequestSeverity = "WARNING"
)

// Defines values for CreateTaskDurationAlertRequestType.
const (
	CreateTaskDurationAlertRequestTypeDAGDURATION   CreateTaskDurationAlertRequestType = "DAG_DURATION"
	CreateTaskDurationAlertRequestTypeDAGFAILURE    CreateTaskDurationAlertRequestType = "DAG_FAILURE"
	CreateTaskDurationAlertRequestTypeDAGSUCCESS    CreateTaskDurationAlertRequestType = "DAG_SUCCESS"
	CreateTaskDurationAlertRequestTypeDAGTIMELINESS CreateTaskDurationAlertRequestType = "DAG_TIMELINESS"
	CreateTaskDurationAlertRequestTypeTASKDURATION  CreateTaskDurationAlertRequestType = "TASK_DURATION"
	CreateTaskDurationAlertRequestTypeTASKFAILURE   CreateTaskDurationAlertRequestType = "TASK_FAILURE"
)

// Defines values for CreateTaskFailureAlertRequestEntityType.
const (
	CreateTaskFailureAlertRequestEntityTypeDEPLOYMENT CreateTaskFailureAlertRequestEntityType = "DEPLOYMENT"
)

// Defines values for CreateTaskFailureAlertRequestSeverity.
const (
	CreateTaskFailureAlertRequestSeverityCRITICAL CreateTaskFailureAlertRequestSeverity = "CRITICAL"
	CreateTaskFailureAlertRequestSeverityINFO     CreateTaskFailureAlertRequestSeverity = "INFO"
	CreateTaskFailureAlertRequestSeverityWARNING  CreateTaskFailureAlertRequestSeverity = "WARNING"
)

// Defines values for CreateTaskFailureAlertRequestType.
const (
	CreateTaskFailureAlertRequestTypeDAGDURATION   CreateTaskFailureAlertRequestType = "DAG_DURATION"
	CreateTaskFailureAlertRequestTypeDAGFAILURE    CreateTaskFailureAlertRequestType = "DAG_FAILURE"
	CreateTaskFailureAlertRequestTypeDAGSUCCESS    CreateTaskFailureAlertRequestType = "DAG_SUCCESS"
	CreateTaskFailureAlertRequestTypeDAGTIMELINESS CreateTaskFailureAlertRequestType = "DAG_TIMELINESS"
	CreateTaskFailureAlertRequestTypeTASKDURATION  CreateTaskFailureAlertRequestType = "TASK_DURATION"
	CreateTaskFailureAlertRequestTypeTASKFAILURE   CreateTaskFailureAlertRequestType = "TASK_FAILURE"
)

// Defines values for PatternMatchEntityType.
const (
	DAGIDTASKID PatternMatchEntityType = "DAG_ID TASK_ID"
)

// Defines values for PatternMatchOperatorType.
const (
	ISISNOTINCLUDESEXCLUDES PatternMatchOperatorType = "IS IS_NOT INCLUDES EXCLUDES"
)

// Defines values for PatternMatchRequestEntityType.
const (
	DAGID  PatternMatchRequestEntityType = "DAG_ID"
	TASKID PatternMatchRequestEntityType = "TASK_ID"
)

// Defines values for PatternMatchRequestOperatorType.
const (
	EXCLUDES PatternMatchRequestOperatorType = "EXCLUDES"
	INCLUDES PatternMatchRequestOperatorType = "INCLUDES"
	IS       PatternMatchRequestOperatorType = "IS"
	ISNOT    PatternMatchRequestOperatorType = "IS_NOT"
)

// Defines values for UpdateDagDurationAlertRequestSeverity.
const (
	UpdateDagDurationAlertRequestSeverityCRITICAL UpdateDagDurationAlertRequestSeverity = "CRITICAL"
	UpdateDagDurationAlertRequestSeverityINFO     UpdateDagDurationAlertRequestSeverity = "INFO"
	UpdateDagDurationAlertRequestSeverityWARNING  UpdateDagDurationAlertRequestSeverity = "WARNING"
)

// Defines values for UpdateDagDurationAlertRequestType.
const (
	UpdateDagDurationAlertRequestTypeDAGDURATION   UpdateDagDurationAlertRequestType = "DAG_DURATION"
	UpdateDagDurationAlertRequestTypeDAGFAILURE    UpdateDagDurationAlertRequestType = "DAG_FAILURE"
	UpdateDagDurationAlertRequestTypeDAGSUCCESS    UpdateDagDurationAlertRequestType = "DAG_SUCCESS"
	UpdateDagDurationAlertRequestTypeDAGTIMELINESS UpdateDagDurationAlertRequestType = "DAG_TIMELINESS"
	UpdateDagDurationAlertRequestTypeTASKDURATION  UpdateDagDurationAlertRequestType = "TASK_DURATION"
	UpdateDagDurationAlertRequestTypeTASKFAILURE   UpdateDagDurationAlertRequestType = "TASK_FAILURE"
)

// Defines values for UpdateDagFailureAlertRequestSeverity.
const (
	UpdateDagFailureAlertRequestSeverityCRITICAL UpdateDagFailureAlertRequestSeverity = "CRITICAL"
	UpdateDagFailureAlertRequestSeverityINFO     UpdateDagFailureAlertRequestSeverity = "INFO"
	UpdateDagFailureAlertRequestSeverityWARNING  UpdateDagFailureAlertRequestSeverity = "WARNING"
)

// Defines values for UpdateDagFailureAlertRequestType.
const (
	UpdateDagFailureAlertRequestTypeDAGDURATION   UpdateDagFailureAlertRequestType = "DAG_DURATION"
	UpdateDagFailureAlertRequestTypeDAGFAILURE    UpdateDagFailureAlertRequestType = "DAG_FAILURE"
	UpdateDagFailureAlertRequestTypeDAGSUCCESS    UpdateDagFailureAlertRequestType = "DAG_SUCCESS"
	UpdateDagFailureAlertRequestTypeDAGTIMELINESS UpdateDagFailureAlertRequestType = "DAG_TIMELINESS"
	UpdateDagFailureAlertRequestTypeTASKDURATION  UpdateDagFailureAlertRequestType = "TASK_DURATION"
	UpdateDagFailureAlertRequestTypeTASKFAILURE   UpdateDagFailureAlertRequestType = "TASK_FAILURE"
)

// Defines values for UpdateDagSuccessAlertRequestSeverity.
const (
	UpdateDagSuccessAlertRequestSeverityCRITICAL UpdateDagSuccessAlertRequestSeverity = "CRITICAL"
	UpdateDagSuccessAlertRequestSeverityINFO     UpdateDagSuccessAlertRequestSeverity = "INFO"
	UpdateDagSuccessAlertRequestSeverityWARNING  UpdateDagSuccessAlertRequestSeverity = "WARNING"
)

// Defines values for UpdateDagSuccessAlertRequestType.
const (
	UpdateDagSuccessAlertRequestTypeDAGDURATION   UpdateDagSuccessAlertRequestType = "DAG_DURATION"
	UpdateDagSuccessAlertRequestTypeDAGFAILURE    UpdateDagSuccessAlertRequestType = "DAG_FAILURE"
	UpdateDagSuccessAlertRequestTypeDAGSUCCESS    UpdateDagSuccessAlertRequestType = "DAG_SUCCESS"
	UpdateDagSuccessAlertRequestTypeDAGTIMELINESS UpdateDagSuccessAlertRequestType = "DAG_TIMELINESS"
	UpdateDagSuccessAlertRequestTypeTASKDURATION  UpdateDagSuccessAlertRequestType = "TASK_DURATION"
	UpdateDagSuccessAlertRequestTypeTASKFAILURE   UpdateDagSuccessAlertRequestType = "TASK_FAILURE"
)

// Defines values for UpdateDagTimelinessAlertRequestSeverity.
const (
	UpdateDagTimelinessAlertRequestSeverityCRITICAL UpdateDagTimelinessAlertRequestSeverity = "CRITICAL"
	UpdateDagTimelinessAlertRequestSeverityINFO     UpdateDagTimelinessAlertRequestSeverity = "INFO"
	UpdateDagTimelinessAlertRequestSeverityWARNING  UpdateDagTimelinessAlertRequestSeverity = "WARNING"
)

// Defines values for UpdateDagTimelinessAlertRequestType.
const (
	UpdateDagTimelinessAlertRequestTypeDAGDURATION   UpdateDagTimelinessAlertRequestType = "DAG_DURATION"
	UpdateDagTimelinessAlertRequestTypeDAGFAILURE    UpdateDagTimelinessAlertRequestType = "DAG_FAILURE"
	UpdateDagTimelinessAlertRequestTypeDAGSUCCESS    UpdateDagTimelinessAlertRequestType = "DAG_SUCCESS"
	UpdateDagTimelinessAlertRequestTypeDAGTIMELINESS UpdateDagTimelinessAlertRequestType = "DAG_TIMELINESS"
	UpdateDagTimelinessAlertRequestTypeTASKDURATION  UpdateDagTimelinessAlertRequestType = "TASK_DURATION"
	UpdateDagTimelinessAlertRequestTypeTASKFAILURE   UpdateDagTimelinessAlertRequestType = "TASK_FAILURE"
)

// Defines values for UpdateTaskDurationAlertRequestSeverity.
const (
	UpdateTaskDurationAlertRequestSeverityCRITICAL UpdateTaskDurationAlertRequestSeverity = "CRITICAL"
	UpdateTaskDurationAlertRequestSeverityINFO     UpdateTaskDurationAlertRequestSeverity = "INFO"
	UpdateTaskDurationAlertRequestSeverityWARNING  UpdateTaskDurationAlertRequestSeverity = "WARNING"
)

// Defines values for UpdateTaskDurationAlertRequestType.
const (
	UpdateTaskDurationAlertRequestTypeDAGDURATION   UpdateTaskDurationAlertRequestType = "DAG_DURATION"
	UpdateTaskDurationAlertRequestTypeDAGFAILURE    UpdateTaskDurationAlertRequestType = "DAG_FAILURE"
	UpdateTaskDurationAlertRequestTypeDAGSUCCESS    UpdateTaskDurationAlertRequestType = "DAG_SUCCESS"
	UpdateTaskDurationAlertRequestTypeDAGTIMELINESS UpdateTaskDurationAlertRequestType = "DAG_TIMELINESS"
	UpdateTaskDurationAlertRequestTypeTASKDURATION  UpdateTaskDurationAlertRequestType = "TASK_DURATION"
	UpdateTaskDurationAlertRequestTypeTASKFAILURE   UpdateTaskDurationAlertRequestType = "TASK_FAILURE"
)

// Defines values for UpdateTaskFailureAlertRequestSeverity.
const (
	CRITICAL UpdateTaskFailureAlertRequestSeverity = "CRITICAL"
	INFO     UpdateTaskFailureAlertRequestSeverity = "INFO"
	WARNING  UpdateTaskFailureAlertRequestSeverity = "WARNING"
)

// Defines values for UpdateTaskFailureAlertRequestType.
const (
	DAGDURATION   UpdateTaskFailureAlertRequestType = "DAG_DURATION"
	DAGFAILURE    UpdateTaskFailureAlertRequestType = "DAG_FAILURE"
	DAGSUCCESS    UpdateTaskFailureAlertRequestType = "DAG_SUCCESS"
	DAGTIMELINESS UpdateTaskFailureAlertRequestType = "DAG_TIMELINESS"
	TASKDURATION  UpdateTaskFailureAlertRequestType = "TASK_DURATION"
	TASKFAILURE   UpdateTaskFailureAlertRequestType = "TASK_FAILURE"
)

// Alert defines model for Alert.
type Alert struct {
	// CreatedAt The time when the alert was created in UTC, formatted as `YYYY-MM-DDTHH:MM:SSZ`.
	CreatedAt time.Time           `json:"createdAt"`
	CreatedBy BasicSubjectProfile `json:"createdBy"`

	// DeploymentId The ID of the deployment the alert is associated with.
	DeploymentId *string `json:"deploymentId,omitempty"`

	// EntityId The ID of the entity the alert is associated with.
	EntityId string `json:"entityId"`

	// EntityName The name of the entity the alert is associated with.
	EntityName *string `json:"entityName,omitempty"`

	// EntityType The type of entity the alert is associated with.
	EntityType AlertEntityType `json:"entityType"`

	// Id The alert's ID.
	Id string `json:"id"`

	// Name The alert's name.
	Name string `json:"name"`

	// NotificationChannels The notification channels to send alerts to.
	NotificationChannels *[]AlertNotificationChannel `json:"notificationChannels,omitempty"`

	// OrganizationId The ID of the organization the alert is associated with.
	OrganizationId string     `json:"organizationId"`
	Rules          AlertRules `json:"rules"`

	// Severity The alert's severity.
	Severity AlertSeverity `json:"severity"`

	// Type The alert's type.
	Type AlertType `json:"type"`

	// UpdatedAt The time when the alert was last updated in UTC, formatted as `YYYY-MM-DDTHH:MM:SSZ`.
	UpdatedAt time.Time           `json:"updatedAt"`
	UpdatedBy BasicSubjectProfile `json:"updatedBy"`

	// WorkspaceId The ID of the workspace the alert is associated with.
	WorkspaceId *string `json:"workspaceId,omitempty"`
}

// AlertEntityType The type of entity the alert is associated with.
type AlertEntityType string

// AlertSeverity The alert's severity.
type AlertSeverity string

// AlertType The alert's type.
type AlertType string

// AlertNotificationChannel defines model for AlertNotificationChannel.
type AlertNotificationChannel struct {
	// CreatedAt The time when the notification channel was created in UTC, formatted as `YYYY-MM-DDTHH:MM:SSZ`.
	CreatedAt time.Time `json:"createdAt"`

	// Definition The definition of the notification.
	Definition interface{} `json:"definition"`

	// DeploymentId The ID of the deployment the notification channel is associated with.
	DeploymentId *string `json:"deploymentId,omitempty"`

	// EntityId The ID of the entity the notification channel is associated with.
	EntityId string `json:"entityId"`

	// EntityType The type of entity the notification channel is associated with.
	EntityType AlertNotificationChannelEntityType `json:"entityType"`

	// Id The ID of the notification channel.
	Id string `json:"id"`

	// Name The name of the notification channel.
	Name string `json:"name"`

	// OrganizationId The ID of the organization the notification channel is associated with.
	OrganizationId string `json:"organizationId"`

	// Type The type of the notification channel.
	Type AlertNotificationChannelType `json:"type"`

	// UpdatedAt The time when the notification channel was last updated in UTC, formatted as `YYYY-MM-DDTHH:MM:SSZ`.
	UpdatedAt time.Time `json:"updatedAt"`

	// WorkspaceId The ID of the workspace the notification channel is associated with.
	WorkspaceId *string `json:"workspaceId,omitempty"`
}

// AlertNotificationChannelEntityType The type of entity the notification channel is associated with.
type AlertNotificationChannelEntityType string

// AlertNotificationChannelType The type of the notification channel.
type AlertNotificationChannelType string

// AlertRules defines model for AlertRules.
type AlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches *[]PatternMatch `json:"patternMatches,omitempty"`

	// Properties The alert's properties used to define the alert.
	Properties interface{} `json:"properties"`
}

// AlertsList defines model for AlertsList.
type AlertsList struct {
	// Alerts The alerts that were created or updated.
	Alerts []Alert `json:"alerts"`
}

// BasicSubjectProfile defines model for BasicSubjectProfile.
type BasicSubjectProfile struct {
	// ApiTokenName The API token's name. Returned only when `SubjectType` is `SERVICEKEY`.
	ApiTokenName *string `json:"apiTokenName,omitempty"`

	// AvatarUrl The URL for the user's profile image. Returned only when `SubjectType` is `USER`.
	AvatarUrl *string `json:"avatarUrl,omitempty"`

	// FullName The subject's full name. Returned only when `SubjectType` is `USER`.
	FullName *string `json:"fullName,omitempty"`

	// Id The subject's ID.
	Id string `json:"id"`

	// SubjectType The subject type.
	SubjectType *BasicSubjectProfileSubjectType `json:"subjectType,omitempty"`

	// Username The subject's username. Returned only when `SubjectType` is `USER`.
	Username *string `json:"username,omitempty"`
}

// BasicSubjectProfileSubjectType The subject type.
type BasicSubjectProfileSubjectType string

// CreateAlertRequest defines model for CreateAlertRequest.
type CreateAlertRequest struct {
	union json.RawMessage
}

// CreateAlertsRequest defines model for CreateAlertsRequest.
type CreateAlertsRequest struct {
	// Alerts The alerts to create. At most 30 per request.
	Alerts []CreateAlertRequest `json:"alerts"`
}

// CreateDagDurationAlertProperties defines model for CreateDagDurationAlertProperties.
type CreateDagDurationAlertProperties struct {
	// DagDurationSeconds The duration of the DAG in seconds. Min 60 (1 minute), max 604800 (7 days).
	DagDurationSeconds int `json:"dagDurationSeconds"`

	// DeploymentId The ID of the deployment to which the alert is scoped.
	DeploymentId string `json:"deploymentId"`
}

// CreateDagDurationAlertRequest defines model for CreateDagDurationAlertRequest.
type CreateDagDurationAlertRequest struct {
	// EntityId The entity ID the alert is associated with.
	EntityId string `json:"entityId"`

	// EntityType The type of entity the alert is scoped to.
	EntityType CreateDagDurationAlertRequestEntityType `json:"entityType"`

	// Name The alert's name.
	Name string `json:"name"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds []string                    `json:"notificationChannelIds"`
	Rules                  CreateDagDurationAlertRules `json:"rules"`

	// Severity The alert's severity.
	Severity CreateDagDurationAlertRequestSeverity `json:"severity"`

	// Type The alert's type.
	Type CreateDagDurationAlertRequestType `json:"type"`
}

// CreateDagDurationAlertRequestEntityType The type of entity the alert is scoped to.
type CreateDagDurationAlertRequestEntityType string

// CreateDagDurationAlertRequestSeverity The alert's severity.
type CreateDagDurationAlertRequestSeverity string

// CreateDagDurationAlertRequestType The alert's type.
type CreateDagDurationAlertRequestType string

// CreateDagDurationAlertRules defines model for CreateDagDurationAlertRules.
type CreateDagDurationAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches []PatternMatchRequest            `json:"patternMatches"`
	Properties     CreateDagDurationAlertProperties `json:"properties"`
}

// CreateDagFailureAlertProperties defines model for CreateDagFailureAlertProperties.
type CreateDagFailureAlertProperties struct {
	// DeploymentId The ID of the deployment to which the alert is scoped.
	DeploymentId string `json:"deploymentId"`
}

// CreateDagFailureAlertRequest defines model for CreateDagFailureAlertRequest.
type CreateDagFailureAlertRequest struct {
	// EntityId The entity ID the alert is associated with.
	EntityId string `json:"entityId"`

	// EntityType The type of entity the alert is scoped to.
	EntityType CreateDagFailureAlertRequestEntityType `json:"entityType"`

	// Name The alert's name.
	Name string `json:"name"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds []string                   `json:"notificationChannelIds"`
	Rules                  CreateDagFailureAlertRules `json:"rules"`

	// Severity The alert's severity.
	Severity CreateDagFailureAlertRequestSeverity `json:"severity"`

	// Type The alert's type.
	Type CreateDagFailureAlertRequestType `json:"type"`
}

// CreateDagFailureAlertRequestEntityType The type of entity the alert is scoped to.
type CreateDagFailureAlertRequestEntityType string

// CreateDagFailureAlertRequestSeverity The alert's severity.
type CreateDagFailureAlertRequestSeverity string

// CreateDagFailureAlertRequestType The alert's type.
type CreateDagFailureAlertRequestType string

// CreateDagFailureAlertRules defines model for CreateDagFailureAlertRules.
type CreateDagFailureAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches []PatternMatchRequest           `json:"patternMatches"`
	Properties     CreateDagFailureAlertProperties `json:"properties"`
}

// CreateDagSuccessAlertProperties defines model for CreateDagSuccessAlertProperties.
type CreateDagSuccessAlertProperties struct {
	// DeploymentId The ID of the deployment to which the alert is scoped.
	DeploymentId string `json:"deploymentId"`
}

// CreateDagSuccessAlertRequest defines model for CreateDagSuccessAlertRequest.
type CreateDagSuccessAlertRequest struct {
	// EntityId The entity ID the alert is associated with.
	EntityId string `json:"entityId"`

	// EntityType The type of entity the alert is scoped to.
	EntityType CreateDagSuccessAlertRequestEntityType `json:"entityType"`

	// Name The alert's name.
	Name string `json:"name"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds []string                   `json:"notificationChannelIds"`
	Rules                  CreateDagSuccessAlertRules `json:"rules"`

	// Severity The alert's severity.
	Severity CreateDagSuccessAlertRequestSeverity `json:"severity"`

	// Type The alert's type.
	Type CreateDagSuccessAlertRequestType `json:"type"`
}

// CreateDagSuccessAlertRequestEntityType The type of entity the alert is scoped to.
type CreateDagSuccessAlertRequestEntityType string

// CreateDagSuccessAlertRequestSeverity The alert's severity.
type CreateDagSuccessAlertRequestSeverity string

// CreateDagSuccessAlertRequestType The alert's type.
type CreateDagSuccessAlertRequestType string

// CreateDagSuccessAlertRules defines model for CreateDagSuccessAlertRules.
type CreateDagSuccessAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches []PatternMatchRequest           `json:"patternMatches"`
	Properties     CreateDagSuccessAlertProperties `json:"properties"`
}

// CreateDagTimelinessAlertProperties defines model for CreateDagTimelinessAlertProperties.
type CreateDagTimelinessAlertProperties struct {
	// DagDeadline The deadline for the DAG in HH:MM 24-hour format, in UTC time.
	DagDeadline string `json:"dagDeadline"`

	// DaysOfWeek The days of the week for the alert.
	DaysOfWeek []string `json:"daysOfWeek"`

	// DeploymentId The ID of the deployment to which the alert is scoped.
	DeploymentId string `json:"deploymentId"`

	// LookBackPeriodSeconds The look-back period in seconds.
	LookBackPeriodSeconds int `json:"lookBackPeriodSeconds"`
}

// CreateDagTimelinessAlertRequest defines model for CreateDagTimelinessAlertRequest.
type CreateDagTimelinessAlertRequest struct {
	// EntityId The entity ID the alert is associated with.
	EntityId string `json:"entityId"`

	// EntityType The type of entity the alert is scoped to.
	EntityType CreateDagTimelinessAlertRequestEntityType `json:"entityType"`

	// Name The alert's name.
	Name string `json:"name"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds []string                      `json:"notificationChannelIds"`
	Rules                  CreateDagTimelinessAlertRules `json:"rules"`

	// Severity The alert's severity.
	Severity CreateDagTimelinessAlertRequestSeverity `json:"severity"`

	// Type The alert's type.
	Type CreateDagTimelinessAlertRequestType `json:"type"`
}

// CreateDagTimelinessAlertRequestEntityType The type of entity the alert is scoped to.
type CreateDagTimelinessAlertRequestEntityType string

// CreateDagTimelinessAlertRequestSeverity The alert's severity.
type CreateDagTimelinessAlertRequestSeverity string

// CreateDagTimelinessAlertRequestType The alert's type.
type CreateDagTimelinessAlertRequestType string

// CreateDagTimelinessAlertRules defines model for CreateDagTimelinessAlertRules.
type CreateDagTimelinessAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches []PatternMatchRequest              `json:"patternMatches"`
	Properties     CreateDagTimelinessAlertProperties `json:"properties"`
}

// CreateTaskDurationAlertProperties defines model for CreateTaskDurationAlertProperties.
type CreateTaskDurationAlertProperties struct {
	// DeploymentId The ID of the deployment to which the alert is scoped.
	DeploymentId string `json:"deploymentId"`

	// TaskDurationSeconds The duration of the Task in seconds.
	TaskDurationSeconds int `json:"taskDurationSeconds"`
}

// CreateTaskDurationAlertRequest defines model for CreateTaskDurationAlertRequest.
type CreateTaskDurationAlertRequest struct {
	// EntityId The entity ID the alert is associated with.
	EntityId string `json:"entityId"`

	// EntityType The type of entity the alert is scoped to.
	EntityType CreateTaskDurationAlertRequestEntityType `json:"entityType"`

	// Name The alert's name.
	Name string `json:"name"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds []string                     `json:"notificationChannelIds"`
	Rules                  CreateTaskDurationAlertRules `json:"rules"`

	// Severity The alert's severity.
	Severity CreateTaskDurationAlertRequestSeverity `json:"severity"`

	// Type The alert's type.
	Type CreateTaskDurationAlertRequestType `json:"type"`
}

// CreateTaskDurationAlertRequestEntityType The type of entity the alert is scoped to.
type CreateTaskDurationAlertRequestEntityType string

// CreateTaskDurationAlertRequestSeverity The alert's severity.
type CreateTaskDurationAlertRequestSeverity string

// CreateTaskDurationAlertRequestType The alert's type.
type CreateTaskDurationAlertRequestType string

// CreateTaskDurationAlertRules defines model for CreateTaskDurationAlertRules.
type CreateTaskDurationAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches []PatternMatchRequest             `json:"patternMatches"`
	Properties     CreateTaskDurationAlertProperties `json:"properties"`
}

// CreateTaskFailureAlertProperties defines model for CreateTaskFailureAlertProperties.
type CreateTaskFailureAlertProperties struct {
	// DeploymentId The ID of the deployment to which the alert is scoped.
	DeploymentId string `json:"deploymentId"`
}

// CreateTaskFailureAlertRequest defines model for CreateTaskFailureAlertRequest.
type CreateTaskFailureAlertRequest struct {
	// EntityId The entity ID the alert is associated with.
	EntityId string `json:"entityId"`

	// EntityType The type of entity the alert is scoped to.
	EntityType CreateTaskFailureAlertRequestEntityType `json:"entityType"`

	// Name The alert's name.
	Name string `json:"name"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds []string                    `json:"notificationChannelIds"`
	Rules                  CreateTaskFailureAlertRules `json:"rules"`

	// Severity The alert's severity.
	Severity CreateTaskFailureAlertRequestSeverity `json:"severity"`

	// Type The alert's type.
	Type CreateTaskFailureAlertRequestType `json:"type"`
}

// CreateTaskFailureAlertRequestEntityType The type of entity the alert is scoped to.
type CreateTaskFailureAlertRequestEntityType string

// CreateTaskFailureAlertRequestSeverity The alert's severity.
type CreateTaskFailureAlertRequestSeverity string

// CreateTaskFailureAlertRequestType The alert's type.
type CreateTaskFailureAlertRequestType string

// CreateTaskFailureAlertRules defines model for CreateTaskFailureAlertRules.
type CreateTaskFailureAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches []PatternMatchRequest            `json:"patternMatches"`
	Properties     CreateTaskFailureAlertProperties `json:"properties"`
}

// DeleteAlertsRequest defines model for DeleteAlertsRequest.
type DeleteAlertsRequest struct {
	// AlertIds The IDs of the alerts to delete. At most 20 per request.
	AlertIds []string `json:"alertIds"`
}

// Error defines model for Error.
type Error struct {
	// FieldErrors FieldErrors carries one entry per failed request-validation constraint.
	// Only present on 400 responses caused by request binding/validation.
	FieldErrors *[]FieldValidationError `json:"fieldErrors,omitempty"`
	Message     string                  `json:"message"`
	RequestId   string                  `json:"requestId"`
	StatusCode  int                     `json:"statusCode"`
}

// FieldValidationError defines model for FieldValidationError.
type FieldValidationError struct {
	Code    string `json:"code"`
	Field   string `json:"field"`
	Message string `json:"message"`
}

// PatternMatch defines model for PatternMatch.
type PatternMatch struct {
	// EntityType The type of entity to match against.
	EntityType PatternMatchEntityType `json:"entityType"`

	// OperatorType The type of operator to use for the pattern match.
	OperatorType PatternMatchOperatorType `json:"operatorType"`

	// Values The values to match against.
	Values []string `json:"values"`
}

// PatternMatchEntityType The type of entity to match against.
type PatternMatchEntityType string

// PatternMatchOperatorType The type of operator to use for the pattern match.
type PatternMatchOperatorType string

// PatternMatchRequest defines model for PatternMatchRequest.
type PatternMatchRequest struct {
	// EntityType The type of entity to match against.
	EntityType PatternMatchRequestEntityType `json:"entityType"`

	// OperatorType The type of operator to use for the pattern match.
	OperatorType PatternMatchRequestOperatorType `json:"operatorType"`

	// Values The values to match against.
	Values []string `json:"values"`
}

// PatternMatchRequestEntityType The type of entity to match against.
type PatternMatchRequestEntityType string

// PatternMatchRequestOperatorType The type of operator to use for the pattern match.
type PatternMatchRequestOperatorType string

// UpdateAlertRequest defines model for UpdateAlertRequest.
type UpdateAlertRequest struct {
	union json.RawMessage
}

// UpdateAlertsRequest defines model for UpdateAlertsRequest.
type UpdateAlertsRequest struct {
	// Alerts The alerts to update. At most 30 per request.
	Alerts []UpdateAlertRequest `json:"alerts"`
}

// UpdateDagDurationAlertProperties defines model for UpdateDagDurationAlertProperties.
type UpdateDagDurationAlertProperties struct {
	// DagDurationSeconds The duration of the DAG in seconds. Min 60 (1 minute), max 604800 (7 days).
	DagDurationSeconds *int `json:"dagDurationSeconds,omitempty"`
}

// UpdateDagDurationAlertRequest defines model for UpdateDagDurationAlertRequest.
type UpdateDagDurationAlertRequest struct {
	// Id The alert's ID. Required when updating alerts in bulk.
	Id *string `json:"id,omitempty"`

	// Name The alert's name.
	Name *string `json:"name,omitempty"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds *[]string                    `json:"notificationChannelIds,omitempty"`
	Rules                  *UpdateDagDurationAlertRules `json:"rules,omitempty"`

	// Severity The alert's severity.
	Severity *UpdateDagDurationAlertRequestSeverity `json:"severity,omitempty"`

	// Type The alert's type.
	Type *UpdateDagDurationAlertRequestType `json:"type,omitempty"`
}

// UpdateDagDurationAlertRequestSeverity The alert's severity.
type UpdateDagDurationAlertRequestSeverity string

// UpdateDagDurationAlertRequestType The alert's type.
type UpdateDagDurationAlertRequestType string

// UpdateDagDurationAlertRules defines model for UpdateDagDurationAlertRules.
type UpdateDagDurationAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches *[]PatternMatchRequest            `json:"patternMatches,omitempty"`
	Properties     *UpdateDagDurationAlertProperties `json:"properties,omitempty"`
}

// UpdateDagFailureAlertRequest defines model for UpdateDagFailureAlertRequest.
type UpdateDagFailureAlertRequest struct {
	// Id The alert's ID. Required when updating alerts in bulk.
	Id *string `json:"id,omitempty"`

	// Name The alert's name.
	Name *string `json:"name,omitempty"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds *[]string                   `json:"notificationChannelIds,omitempty"`
	Rules                  *UpdateDagFailureAlertRules `json:"rules,omitempty"`

	// Severity The alert's severity.
	Severity *UpdateDagFailureAlertRequestSeverity `json:"severity,omitempty"`

	// Type The alert's type.
	Type *UpdateDagFailureAlertRequestType `json:"type,omitempty"`
}

// UpdateDagFailureAlertRequestSeverity The alert's severity.
type UpdateDagFailureAlertRequestSeverity string

// UpdateDagFailureAlertRequestType The alert's type.
type UpdateDagFailureAlertRequestType string

// UpdateDagFailureAlertRules defines model for UpdateDagFailureAlertRules.
type UpdateDagFailureAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches *[]PatternMatchRequest `json:"patternMatches,omitempty"`
}

// UpdateDagSuccessAlertRequest defines model for UpdateDagSuccessAlertRequest.
type UpdateDagSuccessAlertRequest struct {
	// Id The alert's ID. Required when updating alerts in bulk.
	Id *string `json:"id,omitempty"`

	// Name The alert's name.
	Name *string `json:"name,omitempty"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds *[]string                   `json:"notificationChannelIds,omitempty"`
	Rules                  *UpdateDagSuccessAlertRules `json:"rules,omitempty"`

	// Severity The alert's severity.
	Severity *UpdateDagSuccessAlertRequestSeverity `json:"severity,omitempty"`

	// Type The alert's type.
	Type *UpdateDagSuccessAlertRequestType `json:"type,omitempty"`
}

// UpdateDagSuccessAlertRequestSeverity The alert's severity.
type UpdateDagSuccessAlertRequestSeverity string

// UpdateDagSuccessAlertRequestType The alert's type.
type UpdateDagSuccessAlertRequestType string

// UpdateDagSuccessAlertRules defines model for UpdateDagSuccessAlertRules.
type UpdateDagSuccessAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches *[]PatternMatchRequest `json:"patternMatches,omitempty"`
}

// UpdateDagTimelinessAlertProperties defines model for UpdateDagTimelinessAlertProperties.
type UpdateDagTimelinessAlertProperties struct {
	// DagDeadline The deadline for the DAG in HH:MM 24-hour format, in UTC time.
	DagDeadline *string `json:"dagDeadline,omitempty"`

	// DaysOfWeek The days of the week for the alert.
	DaysOfWeek *[]string `json:"daysOfWeek,omitempty"`

	// LookBackPeriodSeconds The look-back period in seconds.
	LookBackPeriodSeconds *int `json:"lookBackPeriodSeconds,omitempty"`
}

// UpdateDagTimelinessAlertRequest defines model for UpdateDagTimelinessAlertRequest.
type UpdateDagTimelinessAlertRequest struct {
	// Id The alert's ID. Required when updating alerts in bulk.
	Id *string `json:"id,omitempty"`

	// Name The alert's name.
	Name *string `json:"name,omitempty"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds *[]string                      `json:"notificationChannelIds,omitempty"`
	Rules                  *UpdateDagTimelinessAlertRules `json:"rules,omitempty"`

	// Severity The alert's severity.
	Severity *UpdateDagTimelinessAlertRequestSeverity `json:"severity,omitempty"`

	// Type The alert's type.
	Type *UpdateDagTimelinessAlertRequestType `json:"type,omitempty"`
}

// UpdateDagTimelinessAlertRequestSeverity The alert's severity.
type UpdateDagTimelinessAlertRequestSeverity string

// UpdateDagTimelinessAlertRequestType The alert's type.
type UpdateDagTimelinessAlertRequestType string

// UpdateDagTimelinessAlertRules defines model for UpdateDagTimelinessAlertRules.
type UpdateDagTimelinessAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches *[]PatternMatchRequest              `json:"patternMatches,omitempty"`
	Properties     *UpdateDagTimelinessAlertProperties `json:"properties,omitempty"`
}

// UpdateTaskDurationAlertProperties defines model for UpdateTaskDurationAlertProperties.
type UpdateTaskDurationAlertProperties struct {
	// TaskDurationSeconds The duration of the Task in seconds.
	TaskDurationSeconds *int `json:"taskDurationSeconds,omitempty"`
}

// UpdateTaskDurationAlertRequest defines model for UpdateTaskDurationAlertRequest.
type UpdateTaskDurationAlertRequest struct {
	// Id The alert's ID. Required when updating alerts in bulk.
	Id *string `json:"id,omitempty"`

	// Name The alert's name.
	Name *string `json:"name,omitempty"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds *[]string                     `json:"notificationChannelIds,omitempty"`
	Rules                  *UpdateTaskDurationAlertRules `json:"rules,omitempty"`

	// Severity The alert's severity.
	Severity *UpdateTaskDurationAlertRequestSeverity `json:"severity,omitempty"`

	// Type The alert's type.
	Type *UpdateTaskDurationAlertRequestType `json:"type,omitempty"`
}

// UpdateTaskDurationAlertRequestSeverity The alert's severity.
type UpdateTaskDurationAlertRequestSeverity string

// UpdateTaskDurationAlertRequestType The alert's type.
type UpdateTaskDurationAlertRequestType string

// UpdateTaskDurationAlertRules defines model for UpdateTaskDurationAlertRules.
type UpdateTaskDurationAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches *[]PatternMatchRequest             `json:"patternMatches,omitempty"`
	Properties     *UpdateTaskDurationAlertProperties `json:"properties,omitempty"`
}

// UpdateTaskFailureAlertRequest defines model for UpdateTaskFailureAlertRequest.
type UpdateTaskFailureAlertRequest struct {
	// Id The alert's ID. Required when updating alerts in bulk.
	Id *string `json:"id,omitempty"`

	// Name The alert's name.
	Name *string `json:"name,omitempty"`

	// NotificationChannelIds The notification channels to send alerts to.
	NotificationChannelIds *[]string                    `json:"notificationChannelIds,omitempty"`
	Rules                  *UpdateTaskFailureAlertRules `json:"rules,omitempty"`

	// Severity The alert's severity.
	Severity *UpdateTaskFailureAlertRequestSeverity `json:"severity,omitempty"`

	// Type The alert's type.
	Type *UpdateTaskFailureAlertRequestType `json:"type,omitempty"`
}

// UpdateTaskFailureAlertRequestSeverity The alert's severity.
type UpdateTaskFailureAlertRequestSeverity string

// UpdateTaskFailureAlertRequestType The alert's type.
type UpdateTaskFailureAlertRequestType string

// UpdateTaskFailureAlertRules defines model for UpdateTaskFailureAlertRules.
type UpdateTaskFailureAlertRules struct {
	// PatternMatches The alert's pattern matches to match against.
	PatternMatches *[]PatternMatchRequest `json:"patternMatches,omitempty"`
}

// LabsListAlertsParams defines parameters for LabsListAlerts.
type LabsListAlertsParams struct {
	// AlertIds A list of IDs for specific alerts to list. The API returns details for all alerts which have been specified in this list. At most 1000.
	AlertIds *[]string `form:"alertIds,omitempty" json:"alertIds,omitempty"`

	// DeploymentIds A list of deployment IDs the alerts belong to. The API returns details for all alerts belonging only to the specified Deployments. At most 1000.
	DeploymentIds *[]string `form:"deploymentIds,omitempty" json:"deploymentIds,omitempty"`

	// Offset The number of results to skip before returning values.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The maximum number of results to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// LabsCreateAlertsJSONRequestBody defines body for LabsCreateAlerts for application/json ContentType.
type LabsCreateAlertsJSONRequestBody = CreateAlertsRequest

// LabsDeleteAlertsJSONRequestBody defines body for LabsDeleteAlerts for application/json ContentType.
type LabsDeleteAlertsJSONRequestBody = DeleteAlertsRequest

// LabsUpdateAlertsJSONRequestBody defines body for LabsUpdateAlerts for application/json ContentType.
type LabsUpdateAlertsJSONRequestBody = UpdateAlertsRequest

// AsCreateDagDurationAlertRequest returns the union data inside the CreateAlertRequest as a CreateDagDurationAlertRequest
func (t CreateAlertRequest) AsCreateDagDurationAlertRequest() (CreateDagDurationAlertRequest, error) {
	var body CreateDagDurationAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateDagDurationAlertRequest overwrites any union data inside the CreateAlertRequest as the provided CreateDagDurationAlertRequest
func (t *CreateAlertRequest) FromCreateDagDurationAlertRequest(v CreateDagDurationAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_DURATION"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeCreateDagDurationAlertRequest performs a merge with any union data inside the CreateAlertRequest, using the provided CreateDagDurationAlertRequest
func (t *CreateAlertRequest) MergeCreateDagDurationAlertRequest(v CreateDagDurationAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_DURATION"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateDagFailureAlertRequest returns the union data inside the CreateAlertRequest as a CreateDagFailureAlertRequest
func (t CreateAlertRequest) AsCreateDagFailureAlertRequest() (CreateDagFailureAlertRequest, error) {
	var body CreateDagFailureAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateDagFailureAlertRequest overwrites any union data inside the CreateAlertRequest as the provided CreateDagFailureAlertRequest
func (t *CreateAlertRequest) FromCreateDagFailureAlertRequest(v CreateDagFailureAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_FAILURE"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeCreateDagFailureAlertRequest performs a merge with any union data inside the CreateAlertRequest, using the provided CreateDagFailureAlertRequest
func (t *CreateAlertRequest) MergeCreateDagFailureAlertRequest(v CreateDagFailureAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_FAILURE"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateDagSuccessAlertRequest returns the union data inside the CreateAlertRequest as a CreateDagSuccessAlertRequest
func (t CreateAlertRequest) AsCreateDagSuccessAlertRequest() (CreateDagSuccessAlertRequest, error) {
	var body CreateDagSuccessAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateDagSuccessAlertRequest overwrites any union data inside the CreateAlertRequest as the provided CreateDagSuccessAlertRequest
func (t *CreateAlertRequest) FromCreateDagSuccessAlertRequest(v CreateDagSuccessAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_SUCCESS"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeCreateDagSuccessAlertRequest performs a merge with any union data inside the CreateAlertRequest, using the provided CreateDagSuccessAlertRequest
func (t *CreateAlertRequest) MergeCreateDagSuccessAlertRequest(v CreateDagSuccessAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_SUCCESS"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateDagTimelinessAlertRequest returns the union data inside the CreateAlertRequest as a CreateDagTimelinessAlertRequest
func (t CreateAlertRequest) AsCreateDagTimelinessAlertRequest() (CreateDagTimelinessAlertRequest, error) {
	var body CreateDagTimelinessAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateDagTimelinessAlertRequest overwrites any union data inside the CreateAlertRequest as the provided CreateDagTimelinessAlertRequest
func (t *CreateAlertRequest) FromCreateDagTimelinessAlertRequest(v CreateDagTimelinessAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_TIMELINESS"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeCreateDagTimelinessAlertRequest performs a merge with any union data inside the CreateAlertRequest, using the provided CreateDagTimelinessAlertRequest
func (t *CreateAlertRequest) MergeCreateDagTimelinessAlertRequest(v CreateDagTimelinessAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_TIMELINESS"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateTaskDurationAlertRequest returns the union data inside the CreateAlertRequest as a CreateTaskDurationAlertRequest
func (t CreateAlertRequest) AsCreateTaskDurationAlertRequest() (CreateTaskDurationAlertRequest, error) {
	var body CreateTaskDurationAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateTaskDurationAlertRequest overwrites any union data inside the CreateAlertRequest as the provided CreateTaskDurationAlertRequest
func (t *CreateAlertRequest) FromCreateTaskDurationAlertRequest(v CreateTaskDurationAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"TASK_DURATION"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeCreateTaskDurationAlertRequest performs a merge with any union data inside the CreateAlertRequest, using the provided CreateTaskDurationAlertRequest
func (t *CreateAlertRequest) MergeCreateTaskDurationAlertRequest(v CreateTaskDurationAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"TASK_DURATION"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateTaskFailureAlertRequest returns the union data inside the CreateAlertRequest as a CreateTaskFailureAlertRequest
func (t CreateAlertRequest) AsCreateTaskFailureAlertRequest() (CreateTaskFailureAlertRequest, error) {
	var body CreateTaskFailureAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateTaskFailureAlertRequest overwrites any union data inside the CreateAlertRequest as the provided CreateTaskFailureAlertRequest
func (t *CreateAlertRequest) FromCreateTaskFailureAlertRequest(v CreateTaskFailureAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"TASK_FAILURE"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeCreateTaskFailureAlertRequest performs a merge with any union data inside the CreateAlertRequest, using the provided CreateTaskFailureAlertRequest
func (t *CreateAlertRequest) MergeCreateTaskFailureAlertRequest(v CreateTaskFailureAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"TASK_FAILURE"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateAlertRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CreateAlertRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "DAG_DURATION":
		return t.AsCreateDagDurationAlertRequest()
	case "DAG_FAILURE":
		return t.AsCreateDagFailureAlertRequest()
	case "DAG_SUCCESS":
		return t.AsCreateDagSuccessAlertRequest()
	case "DAG_TIMELINESS":
		return t.AsCreateDagTimelinessAlertRequest()
	case "TASK_DURATION":
		return t.AsCreateTaskDurationAlertRequest()
	case "TASK_FAILURE":
		return t.AsCreateTaskFailureAlertRequest()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CreateAlertRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateAlertRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsUpdateDagDurationAlertRequest returns the union data inside the UpdateAlertRequest as a UpdateDagDurationAlertRequest
func (t UpdateAlertRequest) AsUpdateDagDurationAlertRequest() (UpdateDagDurationAlertRequest, error) {
	var body UpdateDagDurationAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpdateDagDurationAlertRequest overwrites any union data inside the UpdateAlertRequest as the provided UpdateDagDurationAlertRequest
func (t *UpdateAlertRequest) FromUpdateDagDurationAlertRequest(v UpdateDagDurationAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_DURATION"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeUpdateDagDurationAlertRequest performs a merge with any union data inside the UpdateAlertRequest, using the provided UpdateDagDurationAlertRequest
func (t *UpdateAlertRequest) MergeUpdateDagDurationAlertRequest(v UpdateDagDurationAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_DURATION"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUpdateDagFailureAlertRequest returns the union data inside the UpdateAlertRequest as a UpdateDagFailureAlertRequest
func (t UpdateAlertRequest) AsUpdateDagFailureAlertRequest() (UpdateDagFailureAlertRequest, error) {
	var body UpdateDagFailureAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpdateDagFailureAlertRequest overwrites any union data inside the UpdateAlertRequest as the provided UpdateDagFailureAlertRequest
func (t *UpdateAlertRequest) FromUpdateDagFailureAlertRequest(v UpdateDagFailureAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_FAILURE"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeUpdateDagFailureAlertRequest performs a merge with any union data inside the UpdateAlertRequest, using the provided UpdateDagFailureAlertRequest
func (t *UpdateAlertRequest) MergeUpdateDagFailureAlertRequest(v UpdateDagFailureAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_FAILURE"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUpdateDagSuccessAlertRequest returns the union data inside the UpdateAlertRequest as a UpdateDagSuccessAlertRequest
func (t UpdateAlertRequest) AsUpdateDagSuccessAlertRequest() (UpdateDagSuccessAlertRequest, error) {
	var body UpdateDagSuccessAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpdateDagSuccessAlertRequest overwrites any union data inside the UpdateAlertRequest as the provided UpdateDagSuccessAlertRequest
func (t *UpdateAlertRequest) FromUpdateDagSuccessAlertRequest(v UpdateDagSuccessAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_SUCCESS"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeUpdateDagSuccessAlertRequest performs a merge with any union data inside the UpdateAlertRequest, using the provided UpdateDagSuccessAlertRequest
func (t *UpdateAlertRequest) MergeUpdateDagSuccessAlertRequest(v UpdateDagSuccessAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_SUCCESS"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUpdateDagTimelinessAlertRequest returns the union data inside the UpdateAlertRequest as a UpdateDagTimelinessAlertRequest
func (t UpdateAlertRequest) AsUpdateDagTimelinessAlertRequest() (UpdateDagTimelinessAlertRequest, error) {
	var body UpdateDagTimelinessAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpdateDagTimelinessAlertRequest overwrites any union data inside the UpdateAlertRequest as the provided UpdateDagTimelinessAlertRequest
func (t *UpdateAlertRequest) FromUpdateDagTimelinessAlertRequest(v UpdateDagTimelinessAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_TIMELINESS"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeUpdateDagTimelinessAlertRequest performs a merge with any union data inside the UpdateAlertRequest, using the provided UpdateDagTimelinessAlertRequest
func (t *UpdateAlertRequest) MergeUpdateDagTimelinessAlertRequest(v UpdateDagTimelinessAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"DAG_TIMELINESS"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUpdateTaskDurationAlertRequest returns the union data inside the UpdateAlertRequest as a UpdateTaskDurationAlertRequest
func (t UpdateAlertRequest) AsUpdateTaskDurationAlertRequest() (UpdateTaskDurationAlertRequest, error) {
	var body UpdateTaskDurationAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpdateTaskDurationAlertRequest overwrites any union data inside the UpdateAlertRequest as the provided UpdateTaskDurationAlertRequest
func (t *UpdateAlertRequest) FromUpdateTaskDurationAlertRequest(v UpdateTaskDurationAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"TASK_DURATION"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeUpdateTaskDurationAlertRequest performs a merge with any union data inside the UpdateAlertRequest, using the provided UpdateTaskDurationAlertRequest
func (t *UpdateAlertRequest) MergeUpdateTaskDurationAlertRequest(v UpdateTaskDurationAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"TASK_DURATION"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUpdateTaskFailureAlertRequest returns the union data inside the UpdateAlertRequest as a UpdateTaskFailureAlertRequest
func (t UpdateAlertRequest) AsUpdateTaskFailureAlertRequest() (UpdateTaskFailureAlertRequest, error) {
	var body UpdateTaskFailureAlertRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpdateTaskFailureAlertRequest overwrites any union data inside the UpdateAlertRequest as the provided UpdateTaskFailureAlertRequest
func (t *UpdateAlertRequest) FromUpdateTaskFailureAlertRequest(v UpdateTaskFailureAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"TASK_FAILURE"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	t.union = b
	return err
}

// MergeUpdateTaskFailureAlertRequest performs a merge with any union data inside the UpdateAlertRequest, using the provided UpdateTaskFailureAlertRequest
func (t *UpdateAlertRequest) MergeUpdateTaskFailureAlertRequest(v UpdateTaskFailureAlertRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	// Inject discriminator into the marshaled JSON so this works whether
	// the variant's discriminator field is required (value) or optional (pointer).
	obj := make(map[string]json.RawMessage)
	if err = json.Unmarshal(b, &obj); err != nil {
		return err
	}
	obj["type"] = json.RawMessage(`"TASK_FAILURE"`)
	b, err = json.Marshal(obj)
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UpdateAlertRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t UpdateAlertRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "DAG_DURATION":
		return t.AsUpdateDagDurationAlertRequest()
	case "DAG_FAILURE":
		return t.AsUpdateDagFailureAlertRequest()
	case "DAG_SUCCESS":
		return t.AsUpdateDagSuccessAlertRequest()
	case "DAG_TIMELINESS":
		return t.AsUpdateDagTimelinessAlertRequest()
	case "TASK_DURATION":
		return t.AsUpdateTaskDurationAlertRequest()
	case "TASK_FAILURE":
		return t.AsUpdateTaskFailureAlertRequest()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t UpdateAlertRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UpdateAlertRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// LabsListAlerts request
	LabsListAlerts(ctx context.Context, organizationId string, params *LabsListAlertsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LabsCreateAlertsWithBody request with any body
	LabsCreateAlertsWithBody(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	LabsCreateAlerts(ctx context.Context, organizationId string, body LabsCreateAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LabsDeleteAlertsWithBody request with any body
	LabsDeleteAlertsWithBody(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	LabsDeleteAlerts(ctx context.Context, organizationId string, body LabsDeleteAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LabsUpdateAlertsWithBody request with any body
	LabsUpdateAlertsWithBody(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	LabsUpdateAlerts(ctx context.Context, organizationId string, body LabsUpdateAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Hand-added pending codegen (see allowed_ip_address_ranges.go): LabsListAllowedIpAddressRanges request
	LabsListAllowedIpAddressRanges(ctx context.Context, organizationId string, params *ListAllowedIpAddressRangesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LabsCreateAllowedIpAddressRangesWithBody request with any body
	LabsCreateAllowedIpAddressRangesWithBody(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	LabsCreateAllowedIpAddressRanges(ctx context.Context, organizationId string, body LabsCreateAllowedIpAddressRangesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LabsDeleteAllowedIpAddressRangesWithBody request with any body
	LabsDeleteAllowedIpAddressRangesWithBody(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	LabsDeleteAllowedIpAddressRanges(ctx context.Context, organizationId string, body LabsDeleteAllowedIpAddressRangesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) LabsListAlerts(ctx context.Context, organizationId string, params *LabsListAlertsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLabsListAlertsRequest(c.Server, organizationId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LabsCreateAlertsWithBody(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLabsCreateAlertsRequestWithBody(c.Server, organizationId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LabsCreateAlerts(ctx context.Context, organizationId string, body LabsCreateAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLabsCreateAlertsRequest(c.Server, organizationId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LabsDeleteAlertsWithBody(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLabsDeleteAlertsRequestWithBody(c.Server, organizationId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LabsDeleteAlerts(ctx context.Context, organizationId string, body LabsDeleteAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLabsDeleteAlertsRequest(c.Server, organizationId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LabsUpdateAlertsWithBody(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLabsUpdateAlertsRequestWithBody(c.Server, organizationId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LabsUpdateAlerts(ctx context.Context, organizationId string, body LabsUpdateAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLabsUpdateAlertsRequest(c.Server, organizationId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewLabsListAlertsRequest generates requests for LabsListAlerts
func NewLabsListAlertsRequest(server string, organizationId string, params *LabsListAlertsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/alerts", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.AlertIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "alertIds", runtime.ParamLocationQuery, *params.AlertIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DeploymentIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "deploymentIds", runtime.ParamLocationQuery, *params.DeploymentIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLabsCreateAlertsRequest calls the generic LabsCreateAlerts builder with application/json body
func NewLabsCreateAlertsRequest(server string, organizationId string, body LabsCreateAlertsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLabsCreateAlertsRequestWithBody(server, organizationId, "application/json", bodyReader)
}

// NewLabsCreateAlertsRequestWithBody generates requests for LabsCreateAlerts with any type of body
func NewLabsCreateAlertsRequestWithBody(server string, organizationId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/create-alerts", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewLabsDeleteAlertsRequest calls the generic LabsDeleteAlerts builder with application/json body
func NewLabsDeleteAlertsRequest(server string, organizationId string, body LabsDeleteAlertsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLabsDeleteAlertsRequestWithBody(server, organizationId, "application/json", bodyReader)
}

// NewLabsDeleteAlertsRequestWithBody generates requests for LabsDeleteAlerts with any type of body
func NewLabsDeleteAlertsRequestWithBody(server string, organizationId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/delete-alerts", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewLabsUpdateAlertsRequest calls the generic LabsUpdateAlerts builder with application/json body
func NewLabsUpdateAlertsRequest(server string, organizationId string, body LabsUpdateAlertsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLabsUpdateAlertsRequestWithBody(server, organizationId, "application/json", bodyReader)
}

// NewLabsUpdateAlertsRequestWithBody generates requests for LabsUpdateAlerts with any type of body
func NewLabsUpdateAlertsRequestWithBody(server string, organizationId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/update-alerts", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// LabsListAlertsWithResponse request
	LabsListAlertsWithResponse(ctx context.Context, organizationId string, params *LabsListAlertsParams, reqEditors ...RequestEditorFn) (*LabsListAlertsResponse, error)

	// LabsCreateAlertsWithBodyWithResponse request with any body
	LabsCreateAlertsWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LabsCreateAlertsResponse, error)

	LabsCreateAlertsWithResponse(ctx context.Context, organizationId string, body LabsCreateAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*LabsCreateAlertsResponse, error)

	// LabsDeleteAlertsWithBodyWithResponse request with any body
	LabsDeleteAlertsWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LabsDeleteAlertsResponse, error)

	LabsDeleteAlertsWithResponse(ctx context.Context, organizationId string, body LabsDeleteAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*LabsDeleteAlertsResponse, error)

	// LabsUpdateAlertsWithBodyWithResponse request with any body
	LabsUpdateAlertsWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LabsUpdateAlertsResponse, error)

	LabsUpdateAlertsWithResponse(ctx context.Context, organizationId string, body LabsUpdateAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*LabsUpdateAlertsResponse, error)
}

type LabsListAlertsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AlertsList
	JSON400      *Error
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r LabsListAlertsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LabsListAlertsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LabsCreateAlertsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AlertsList
	JSON400      *Error
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r LabsCreateAlertsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LabsCreateAlertsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LabsDeleteAlertsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r LabsDeleteAlertsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LabsDeleteAlertsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LabsUpdateAlertsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AlertsList
	JSON400      *Error
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r LabsUpdateAlertsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LabsUpdateAlertsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// LabsListAlertsWithResponse request returning *LabsListAlertsResponse
func (c *ClientWithResponses) LabsListAlertsWithResponse(ctx context.Context, organizationId string, params *LabsListAlertsParams, reqEditors ...RequestEditorFn) (*LabsListAlertsResponse, error) {
	rsp, err := c.LabsListAlerts(ctx, organizationId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLabsListAlertsResponse(rsp)
}

// LabsCreateAlertsWithBodyWithResponse request with arbitrary body returning *LabsCreateAlertsResponse
func (c *ClientWithResponses) LabsCreateAlertsWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LabsCreateAlertsResponse, error) {
	rsp, err := c.LabsCreateAlertsWithBody(ctx, organizationId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLabsCreateAlertsResponse(rsp)
}

func (c *ClientWithResponses) LabsCreateAlertsWithResponse(ctx context.Context, organizationId string, body LabsCreateAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*LabsCreateAlertsResponse, error) {
	rsp, err := c.LabsCreateAlerts(ctx, organizationId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLabsCreateAlertsResponse(rsp)
}

// LabsDeleteAlertsWithBodyWithResponse request with arbitrary body returning *LabsDeleteAlertsResponse
func (c *ClientWithResponses) LabsDeleteAlertsWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LabsDeleteAlertsResponse, error) {
	rsp, err := c.LabsDeleteAlertsWithBody(ctx, organizationId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLabsDeleteAlertsResponse(rsp)
}

func (c *ClientWithResponses) LabsDeleteAlertsWithResponse(ctx context.Context, organizationId string, body LabsDeleteAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*LabsDeleteAlertsResponse, error) {
	rsp, err := c.LabsDeleteAlerts(ctx, organizationId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLabsDeleteAlertsResponse(rsp)
}

// LabsUpdateAlertsWithBodyWithResponse request with arbitrary body returning *LabsUpdateAlertsResponse
func (c *ClientWithResponses) LabsUpdateAlertsWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LabsUpdateAlertsResponse, error) {
	rsp, err := c.LabsUpdateAlertsWithBody(ctx, organizationId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLabsUpdateAlertsResponse(rsp)
}

func (c *ClientWithResponses) LabsUpdateAlertsWithResponse(ctx context.Context, organizationId string, body LabsUpdateAlertsJSONRequestBody, reqEditors ...RequestEditorFn) (*LabsUpdateAlertsResponse, error) {
	rsp, err := c.LabsUpdateAlerts(ctx, organizationId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLabsUpdateAlertsResponse(rsp)
}

// ParseLabsListAlertsResponse parses an HTTP response from a LabsListAlertsWithResponse call
func ParseLabsListAlertsResponse(rsp *http.Response) (*LabsListAlertsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LabsListAlertsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AlertsList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseLabsCreateAlertsResponse parses an HTTP response from a LabsCreateAlertsWithResponse call
func ParseLabsCreateAlertsResponse(rsp *http.Response) (*LabsCreateAlertsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LabsCreateAlertsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AlertsList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseLabsDeleteAlertsResponse parses an HTTP response from a LabsDeleteAlertsWithResponse call
func ParseLabsDeleteAlertsResponse(rsp *http.Response) (*LabsDeleteAlertsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LabsDeleteAlertsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseLabsUpdateAlertsResponse parses an HTTP response from a LabsUpdateAlertsWithResponse call
func ParseLabsUpdateAlertsResponse(rsp *http.Response) (*LabsUpdateAlertsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LabsUpdateAlertsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AlertsList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
