// Code generated by mockery v2.35.3. DO NOT EDIT.

package mocks_platform

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	platform "github.com/astronomer/terraform-provider-astro/internal/clients/platform"
)

// ClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type ClientWithResponsesInterface struct {
	mock.Mock
}

// CreateAlertWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateAlertWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.CreateAlertResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateAlertResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.CreateAlertResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) *platform.CreateAlertResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateAlertResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateAlertWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateAlertWithResponse(ctx context.Context, organizationId string, body platform.CreateAlertRequest, reqEditors ...platform.RequestEditorFn) (*platform.CreateAlertResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateAlertResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateAlertRequest, ...platform.RequestEditorFn) (*platform.CreateAlertResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateAlertRequest, ...platform.RequestEditorFn) *platform.CreateAlertResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateAlertResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, platform.CreateAlertRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateClusterWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateClusterWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.CreateClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.CreateClusterResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) *platform.CreateClusterResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateClusterWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateClusterWithResponse(ctx context.Context, organizationId string, body platform.CreateClusterRequest, reqEditors ...platform.RequestEditorFn) (*platform.CreateClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateClusterRequest, ...platform.RequestEditorFn) (*platform.CreateClusterResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateClusterRequest, ...platform.RequestEditorFn) *platform.CreateClusterResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, platform.CreateClusterRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDeploymentWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateDeploymentWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.CreateDeploymentResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateDeploymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.CreateDeploymentResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) *platform.CreateDeploymentResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateDeploymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDeploymentWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateDeploymentWithResponse(ctx context.Context, organizationId string, body platform.CreateDeploymentRequest, reqEditors ...platform.RequestEditorFn) (*platform.CreateDeploymentResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateDeploymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateDeploymentRequest, ...platform.RequestEditorFn) (*platform.CreateDeploymentResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateDeploymentRequest, ...platform.RequestEditorFn) *platform.CreateDeploymentResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateDeploymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, platform.CreateDeploymentRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateEnvironmentObjectWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.CreateEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.CreateEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) *platform.CreateEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateEnvironmentObjectWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateEnvironmentObjectWithResponse(ctx context.Context, organizationId string, body platform.CreateEnvironmentObjectRequest, reqEditors ...platform.RequestEditorFn) (*platform.CreateEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateEnvironmentObjectRequest, ...platform.RequestEditorFn) (*platform.CreateEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateEnvironmentObjectRequest, ...platform.RequestEditorFn) *platform.CreateEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, platform.CreateEnvironmentObjectRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateNotificationChannelWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateNotificationChannelWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.CreateNotificationChannelResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateNotificationChannelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.CreateNotificationChannelResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) *platform.CreateNotificationChannelResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateNotificationChannelResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateNotificationChannelWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateNotificationChannelWithResponse(ctx context.Context, organizationId string, body platform.CreateNotificationChannelRequest, reqEditors ...platform.RequestEditorFn) (*platform.CreateNotificationChannelResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateNotificationChannelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateNotificationChannelRequest, ...platform.RequestEditorFn) (*platform.CreateNotificationChannelResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateNotificationChannelRequest, ...platform.RequestEditorFn) *platform.CreateNotificationChannelResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateNotificationChannelResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, platform.CreateNotificationChannelRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateWorkspaceWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateWorkspaceWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.CreateWorkspaceResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateWorkspaceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.CreateWorkspaceResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) *platform.CreateWorkspaceResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateWorkspaceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateWorkspaceWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateWorkspaceWithResponse(ctx context.Context, organizationId string, body platform.CreateWorkspaceRequest, reqEditors ...platform.RequestEditorFn) (*platform.CreateWorkspaceResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.CreateWorkspaceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateWorkspaceRequest, ...platform.RequestEditorFn) (*platform.CreateWorkspaceResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.CreateWorkspaceRequest, ...platform.RequestEditorFn) *platform.CreateWorkspaceResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.CreateWorkspaceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, platform.CreateWorkspaceRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAlertWithResponse provides a mock function with given fields: ctx, organizationId, alertId, reqEditors
func (_m *ClientWithResponsesInterface) DeleteAlertWithResponse(ctx context.Context, organizationId string, alertId string, reqEditors ...platform.RequestEditorFn) (*platform.DeleteAlertResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, alertId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.DeleteAlertResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.DeleteAlertResponse, error)); ok {
		return rf(ctx, organizationId, alertId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.DeleteAlertResponse); ok {
		r0 = rf(ctx, organizationId, alertId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.DeleteAlertResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, alertId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteClusterWithResponse provides a mock function with given fields: ctx, organizationId, clusterId, reqEditors
func (_m *ClientWithResponsesInterface) DeleteClusterWithResponse(ctx context.Context, organizationId string, clusterId string, reqEditors ...platform.RequestEditorFn) (*platform.DeleteClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, clusterId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.DeleteClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.DeleteClusterResponse, error)); ok {
		return rf(ctx, organizationId, clusterId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.DeleteClusterResponse); ok {
		r0 = rf(ctx, organizationId, clusterId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.DeleteClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, clusterId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDeploymentHibernationOverrideWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, reqEditors
func (_m *ClientWithResponsesInterface) DeleteDeploymentHibernationOverrideWithResponse(ctx context.Context, organizationId string, deploymentId string, reqEditors ...platform.RequestEditorFn) (*platform.DeleteDeploymentHibernationOverrideResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.DeleteDeploymentHibernationOverrideResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.DeleteDeploymentHibernationOverrideResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.DeleteDeploymentHibernationOverrideResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.DeleteDeploymentHibernationOverrideResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDeploymentWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, reqEditors
func (_m *ClientWithResponsesInterface) DeleteDeploymentWithResponse(ctx context.Context, organizationId string, deploymentId string, reqEditors ...platform.RequestEditorFn) (*platform.DeleteDeploymentResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.DeleteDeploymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.DeleteDeploymentResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.DeleteDeploymentResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.DeleteDeploymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEnvironmentObjectWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, reqEditors
func (_m *ClientWithResponsesInterface) DeleteEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...platform.RequestEditorFn) (*platform.DeleteEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.DeleteEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.DeleteEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.DeleteEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.DeleteEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNotificationChannelWithResponse provides a mock function with given fields: ctx, organizationId, notificationChannelId, reqEditors
func (_m *ClientWithResponsesInterface) DeleteNotificationChannelWithResponse(ctx context.Context, organizationId string, notificationChannelId string, reqEditors ...platform.RequestEditorFn) (*platform.DeleteNotificationChannelResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, notificationChannelId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.DeleteNotificationChannelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.DeleteNotificationChannelResponse, error)); ok {
		return rf(ctx, organizationId, notificationChannelId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.DeleteNotificationChannelResponse); ok {
		r0 = rf(ctx, organizationId, notificationChannelId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.DeleteNotificationChannelResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, notificationChannelId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteWorkspaceWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, reqEditors
func (_m *ClientWithResponsesInterface) DeleteWorkspaceWithResponse(ctx context.Context, organizationId string, workspaceId string, reqEditors ...platform.RequestEditorFn) (*platform.DeleteWorkspaceResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.DeleteWorkspaceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.DeleteWorkspaceResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.DeleteWorkspaceResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.DeleteWorkspaceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExcludeLinkingEnvironmentObjectWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) ExcludeLinkingEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.ExcludeLinkingEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.ExcludeLinkingEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.ExcludeLinkingEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) *platform.ExcludeLinkingEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.ExcludeLinkingEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExcludeLinkingEnvironmentObjectWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, body, reqEditors
func (_m *ClientWithResponsesInterface) ExcludeLinkingEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, body platform.ExcludeLinkEnvironmentObjectRequest, reqEditors ...platform.RequestEditorFn) (*platform.ExcludeLinkingEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.ExcludeLinkingEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.ExcludeLinkEnvironmentObjectRequest, ...platform.RequestEditorFn) (*platform.ExcludeLinkingEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.ExcludeLinkEnvironmentObjectRequest, ...platform.RequestEditorFn) *platform.ExcludeLinkingEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.ExcludeLinkingEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, platform.ExcludeLinkEnvironmentObjectRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlertWithResponse provides a mock function with given fields: ctx, organizationId, alertId, reqEditors
func (_m *ClientWithResponsesInterface) GetAlertWithResponse(ctx context.Context, organizationId string, alertId string, reqEditors ...platform.RequestEditorFn) (*platform.GetAlertResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, alertId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.GetAlertResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.GetAlertResponse, error)); ok {
		return rf(ctx, organizationId, alertId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.GetAlertResponse); ok {
		r0 = rf(ctx, organizationId, alertId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.GetAlertResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, alertId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClusterOptionsWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) GetClusterOptionsWithResponse(ctx context.Context, organizationId string, params *platform.GetClusterOptionsParams, reqEditors ...platform.RequestEditorFn) (*platform.GetClusterOptionsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.GetClusterOptionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.GetClusterOptionsParams, ...platform.RequestEditorFn) (*platform.GetClusterOptionsResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.GetClusterOptionsParams, ...platform.RequestEditorFn) *platform.GetClusterOptionsResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.GetClusterOptionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *platform.GetClusterOptionsParams, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClusterWithResponse provides a mock function with given fields: ctx, organizationId, clusterId, reqEditors
func (_m *ClientWithResponsesInterface) GetClusterWithResponse(ctx context.Context, organizationId string, clusterId string, reqEditors ...platform.RequestEditorFn) (*platform.GetClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, clusterId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.GetClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.GetClusterResponse, error)); ok {
		return rf(ctx, organizationId, clusterId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.GetClusterResponse); ok {
		r0 = rf(ctx, organizationId, clusterId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.GetClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, clusterId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeploymentOptionsWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) GetDeploymentOptionsWithResponse(ctx context.Context, organizationId string, params *platform.GetDeploymentOptionsParams, reqEditors ...platform.RequestEditorFn) (*platform.GetDeploymentOptionsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.GetDeploymentOptionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.GetDeploymentOptionsParams, ...platform.RequestEditorFn) (*platform.GetDeploymentOptionsResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.GetDeploymentOptionsParams, ...platform.RequestEditorFn) *platform.GetDeploymentOptionsResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.GetDeploymentOptionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *platform.GetDeploymentOptionsParams, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeploymentWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, reqEditors
func (_m *ClientWithResponsesInterface) GetDeploymentWithResponse(ctx context.Context, organizationId string, deploymentId string, reqEditors ...platform.RequestEditorFn) (*platform.GetDeploymentResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.GetDeploymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.GetDeploymentResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.GetDeploymentResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.GetDeploymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEnvironmentObjectWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, reqEditors
func (_m *ClientWithResponsesInterface) GetEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...platform.RequestEditorFn) (*platform.GetEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.GetEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.GetEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.GetEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.GetEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotificationChannelWithResponse provides a mock function with given fields: ctx, organizationId, notificationChannelId, reqEditors
func (_m *ClientWithResponsesInterface) GetNotificationChannelWithResponse(ctx context.Context, organizationId string, notificationChannelId string, reqEditors ...platform.RequestEditorFn) (*platform.GetNotificationChannelResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, notificationChannelId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.GetNotificationChannelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.GetNotificationChannelResponse, error)); ok {
		return rf(ctx, organizationId, notificationChannelId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.GetNotificationChannelResponse); ok {
		r0 = rf(ctx, organizationId, notificationChannelId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.GetNotificationChannelResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, notificationChannelId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationAuditLogsWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) GetOrganizationAuditLogsWithResponse(ctx context.Context, organizationId string, params *platform.GetOrganizationAuditLogsParams, reqEditors ...platform.RequestEditorFn) (*platform.GetOrganizationAuditLogsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.GetOrganizationAuditLogsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.GetOrganizationAuditLogsParams, ...platform.RequestEditorFn) (*platform.GetOrganizationAuditLogsResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.GetOrganizationAuditLogsParams, ...platform.RequestEditorFn) *platform.GetOrganizationAuditLogsResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.GetOrganizationAuditLogsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *platform.GetOrganizationAuditLogsParams, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) GetOrganizationWithResponse(ctx context.Context, organizationId string, params *platform.GetOrganizationParams, reqEditors ...platform.RequestEditorFn) (*platform.GetOrganizationResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.GetOrganizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.GetOrganizationParams, ...platform.RequestEditorFn) (*platform.GetOrganizationResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.GetOrganizationParams, ...platform.RequestEditorFn) *platform.GetOrganizationResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.GetOrganizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *platform.GetOrganizationParams, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspaceWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, reqEditors
func (_m *ClientWithResponsesInterface) GetWorkspaceWithResponse(ctx context.Context, organizationId string, workspaceId string, reqEditors ...platform.RequestEditorFn) (*platform.GetWorkspaceResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.GetWorkspaceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) (*platform.GetWorkspaceResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform.RequestEditorFn) *platform.GetWorkspaceResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.GetWorkspaceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAlertsWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListAlertsWithResponse(ctx context.Context, organizationId string, params *platform.ListAlertsParams, reqEditors ...platform.RequestEditorFn) (*platform.ListAlertsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.ListAlertsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListAlertsParams, ...platform.RequestEditorFn) (*platform.ListAlertsResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListAlertsParams, ...platform.RequestEditorFn) *platform.ListAlertsResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.ListAlertsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *platform.ListAlertsParams, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListClustersWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListClustersWithResponse(ctx context.Context, organizationId string, params *platform.ListClustersParams, reqEditors ...platform.RequestEditorFn) (*platform.ListClustersResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.ListClustersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListClustersParams, ...platform.RequestEditorFn) (*platform.ListClustersResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListClustersParams, ...platform.RequestEditorFn) *platform.ListClustersResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.ListClustersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *platform.ListClustersParams, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDeploymentsWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListDeploymentsWithResponse(ctx context.Context, organizationId string, params *platform.ListDeploymentsParams, reqEditors ...platform.RequestEditorFn) (*platform.ListDeploymentsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.ListDeploymentsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListDeploymentsParams, ...platform.RequestEditorFn) (*platform.ListDeploymentsResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListDeploymentsParams, ...platform.RequestEditorFn) *platform.ListDeploymentsResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.ListDeploymentsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *platform.ListDeploymentsParams, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEnvironmentObjectsWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListEnvironmentObjectsWithResponse(ctx context.Context, organizationId string, params *platform.ListEnvironmentObjectsParams, reqEditors ...platform.RequestEditorFn) (*platform.ListEnvironmentObjectsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.ListEnvironmentObjectsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListEnvironmentObjectsParams, ...platform.RequestEditorFn) (*platform.ListEnvironmentObjectsResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListEnvironmentObjectsParams, ...platform.RequestEditorFn) *platform.ListEnvironmentObjectsResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.ListEnvironmentObjectsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *platform.ListEnvironmentObjectsParams, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListNotificationChannelsWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListNotificationChannelsWithResponse(ctx context.Context, organizationId string, params *platform.ListNotificationChannelsParams, reqEditors ...platform.RequestEditorFn) (*platform.ListNotificationChannelsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.ListNotificationChannelsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListNotificationChannelsParams, ...platform.RequestEditorFn) (*platform.ListNotificationChannelsResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListNotificationChannelsParams, ...platform.RequestEditorFn) *platform.ListNotificationChannelsResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.ListNotificationChannelsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *platform.ListNotificationChannelsParams, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrganizationsWithResponse provides a mock function with given fields: ctx, params, reqEditors
func (_m *ClientWithResponsesInterface) ListOrganizationsWithResponse(ctx context.Context, params *platform.ListOrganizationsParams, reqEditors ...platform.RequestEditorFn) (*platform.ListOrganizationsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.ListOrganizationsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *platform.ListOrganizationsParams, ...platform.RequestEditorFn) (*platform.ListOrganizationsResponse, error)); ok {
		return rf(ctx, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *platform.ListOrganizationsParams, ...platform.RequestEditorFn) *platform.ListOrganizationsResponse); ok {
		r0 = rf(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.ListOrganizationsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *platform.ListOrganizationsParams, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWorkspacesWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListWorkspacesWithResponse(ctx context.Context, organizationId string, params *platform.ListWorkspacesParams, reqEditors ...platform.RequestEditorFn) (*platform.ListWorkspacesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.ListWorkspacesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListWorkspacesParams, ...platform.RequestEditorFn) (*platform.ListWorkspacesResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform.ListWorkspacesParams, ...platform.RequestEditorFn) *platform.ListWorkspacesResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.ListWorkspacesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *platform.ListWorkspacesParams, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAlertWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, alertId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateAlertWithBodyWithResponse(ctx context.Context, organizationId string, alertId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.UpdateAlertResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, alertId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateAlertResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.UpdateAlertResponse, error)); ok {
		return rf(ctx, organizationId, alertId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) *platform.UpdateAlertResponse); ok {
		r0 = rf(ctx, organizationId, alertId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateAlertResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, alertId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAlertWithResponse provides a mock function with given fields: ctx, organizationId, alertId, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateAlertWithResponse(ctx context.Context, organizationId string, alertId string, body platform.UpdateAlertRequest, reqEditors ...platform.RequestEditorFn) (*platform.UpdateAlertResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, alertId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateAlertResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateAlertRequest, ...platform.RequestEditorFn) (*platform.UpdateAlertResponse, error)); ok {
		return rf(ctx, organizationId, alertId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateAlertRequest, ...platform.RequestEditorFn) *platform.UpdateAlertResponse); ok {
		r0 = rf(ctx, organizationId, alertId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateAlertResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, platform.UpdateAlertRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, alertId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateClusterWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, clusterId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateClusterWithBodyWithResponse(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.UpdateClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, clusterId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.UpdateClusterResponse, error)); ok {
		return rf(ctx, organizationId, clusterId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) *platform.UpdateClusterResponse); ok {
		r0 = rf(ctx, organizationId, clusterId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, clusterId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateClusterWithResponse provides a mock function with given fields: ctx, organizationId, clusterId, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateClusterWithResponse(ctx context.Context, organizationId string, clusterId string, body platform.UpdateClusterRequest, reqEditors ...platform.RequestEditorFn) (*platform.UpdateClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, clusterId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateClusterRequest, ...platform.RequestEditorFn) (*platform.UpdateClusterResponse, error)); ok {
		return rf(ctx, organizationId, clusterId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateClusterRequest, ...platform.RequestEditorFn) *platform.UpdateClusterResponse); ok {
		r0 = rf(ctx, organizationId, clusterId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, platform.UpdateClusterRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, clusterId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDeploymentHibernationOverrideWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateDeploymentHibernationOverrideWithBodyWithResponse(ctx context.Context, organizationId string, deploymentId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.UpdateDeploymentHibernationOverrideResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateDeploymentHibernationOverrideResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.UpdateDeploymentHibernationOverrideResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) *platform.UpdateDeploymentHibernationOverrideResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateDeploymentHibernationOverrideResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDeploymentHibernationOverrideWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateDeploymentHibernationOverrideWithResponse(ctx context.Context, organizationId string, deploymentId string, body platform.OverrideDeploymentHibernationBody, reqEditors ...platform.RequestEditorFn) (*platform.UpdateDeploymentHibernationOverrideResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateDeploymentHibernationOverrideResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.OverrideDeploymentHibernationBody, ...platform.RequestEditorFn) (*platform.UpdateDeploymentHibernationOverrideResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.OverrideDeploymentHibernationBody, ...platform.RequestEditorFn) *platform.UpdateDeploymentHibernationOverrideResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateDeploymentHibernationOverrideResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, platform.OverrideDeploymentHibernationBody, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDeploymentWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateDeploymentWithBodyWithResponse(ctx context.Context, organizationId string, deploymentId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.UpdateDeploymentResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateDeploymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.UpdateDeploymentResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) *platform.UpdateDeploymentResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateDeploymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDeploymentWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateDeploymentWithResponse(ctx context.Context, organizationId string, deploymentId string, body platform.UpdateDeploymentRequest, reqEditors ...platform.RequestEditorFn) (*platform.UpdateDeploymentResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateDeploymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateDeploymentRequest, ...platform.RequestEditorFn) (*platform.UpdateDeploymentResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateDeploymentRequest, ...platform.RequestEditorFn) *platform.UpdateDeploymentResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateDeploymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, platform.UpdateDeploymentRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEnvironmentObjectWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.UpdateEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.UpdateEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) *platform.UpdateEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEnvironmentObjectWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, body platform.UpdateEnvironmentObjectRequest, reqEditors ...platform.RequestEditorFn) (*platform.UpdateEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateEnvironmentObjectRequest, ...platform.RequestEditorFn) (*platform.UpdateEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateEnvironmentObjectRequest, ...platform.RequestEditorFn) *platform.UpdateEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, platform.UpdateEnvironmentObjectRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNotificationChannelWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, notificationChannelId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateNotificationChannelWithBodyWithResponse(ctx context.Context, organizationId string, notificationChannelId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.UpdateNotificationChannelResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, notificationChannelId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateNotificationChannelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.UpdateNotificationChannelResponse, error)); ok {
		return rf(ctx, organizationId, notificationChannelId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) *platform.UpdateNotificationChannelResponse); ok {
		r0 = rf(ctx, organizationId, notificationChannelId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateNotificationChannelResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, notificationChannelId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNotificationChannelWithResponse provides a mock function with given fields: ctx, organizationId, notificationChannelId, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateNotificationChannelWithResponse(ctx context.Context, organizationId string, notificationChannelId string, body platform.UpdateNotificationChannelRequest, reqEditors ...platform.RequestEditorFn) (*platform.UpdateNotificationChannelResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, notificationChannelId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateNotificationChannelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateNotificationChannelRequest, ...platform.RequestEditorFn) (*platform.UpdateNotificationChannelResponse, error)); ok {
		return rf(ctx, organizationId, notificationChannelId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateNotificationChannelRequest, ...platform.RequestEditorFn) *platform.UpdateNotificationChannelResponse); ok {
		r0 = rf(ctx, organizationId, notificationChannelId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateNotificationChannelResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, platform.UpdateNotificationChannelRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, notificationChannelId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrganizationWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateOrganizationWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.UpdateOrganizationResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateOrganizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.UpdateOrganizationResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) *platform.UpdateOrganizationResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateOrganizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrganizationWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateOrganizationWithResponse(ctx context.Context, organizationId string, body platform.UpdateOrganizationRequest, reqEditors ...platform.RequestEditorFn) (*platform.UpdateOrganizationResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateOrganizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.UpdateOrganizationRequest, ...platform.RequestEditorFn) (*platform.UpdateOrganizationResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, platform.UpdateOrganizationRequest, ...platform.RequestEditorFn) *platform.UpdateOrganizationResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateOrganizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, platform.UpdateOrganizationRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWorkspaceWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateWorkspaceWithBodyWithResponse(ctx context.Context, organizationId string, workspaceId string, contentType string, body io.Reader, reqEditors ...platform.RequestEditorFn) (*platform.UpdateWorkspaceResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateWorkspaceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) (*platform.UpdateWorkspaceResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) *platform.UpdateWorkspaceResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateWorkspaceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWorkspaceWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateWorkspaceWithResponse(ctx context.Context, organizationId string, workspaceId string, body platform.UpdateWorkspaceRequest, reqEditors ...platform.RequestEditorFn) (*platform.UpdateWorkspaceResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *platform.UpdateWorkspaceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateWorkspaceRequest, ...platform.RequestEditorFn) (*platform.UpdateWorkspaceResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform.UpdateWorkspaceRequest, ...platform.RequestEditorFn) *platform.UpdateWorkspaceResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform.UpdateWorkspaceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, platform.UpdateWorkspaceRequest, ...platform.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientWithResponsesInterface creates a new instance of ClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientWithResponsesInterface {
	mock := &ClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
