// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks_labs

import (
	context "context"
	io "io"

	labs "github.com/astronomer/terraform-provider-astro/internal/clients/labs"
	mock "github.com/stretchr/testify/mock"
)

// ClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type ClientWithResponsesInterface struct {
	mock.Mock
}

// LabsCreateAlertsWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) LabsCreateAlertsWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...labs.RequestEditorFn) (*labs.LabsCreateAlertsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabsCreateAlertsWithBodyWithResponse")
	}

	var r0 *labs.LabsCreateAlertsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) (*labs.LabsCreateAlertsResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) *labs.LabsCreateAlertsResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labs.LabsCreateAlertsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabsCreateAlertsWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) LabsCreateAlertsWithResponse(ctx context.Context, organizationId string, body labs.CreateAlertsRequest, reqEditors ...labs.RequestEditorFn) (*labs.LabsCreateAlertsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabsCreateAlertsWithResponse")
	}

	var r0 *labs.LabsCreateAlertsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, labs.CreateAlertsRequest, ...labs.RequestEditorFn) (*labs.LabsCreateAlertsResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, labs.CreateAlertsRequest, ...labs.RequestEditorFn) *labs.LabsCreateAlertsResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labs.LabsCreateAlertsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, labs.CreateAlertsRequest, ...labs.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabsCreateAllowedIpAddressRangesWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) LabsCreateAllowedIpAddressRangesWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...labs.RequestEditorFn) (*labs.LabsCreateAllowedIpAddressRangesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabsCreateAllowedIpAddressRangesWithBodyWithResponse")
	}

	var r0 *labs.LabsCreateAllowedIpAddressRangesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) (*labs.LabsCreateAllowedIpAddressRangesResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) *labs.LabsCreateAllowedIpAddressRangesResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labs.LabsCreateAllowedIpAddressRangesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabsCreateAllowedIpAddressRangesWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) LabsCreateAllowedIpAddressRangesWithResponse(ctx context.Context, organizationId string, body labs.BulkCreateAllowedIpAddressRangesRequest, reqEditors ...labs.RequestEditorFn) (*labs.LabsCreateAllowedIpAddressRangesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabsCreateAllowedIpAddressRangesWithResponse")
	}

	var r0 *labs.LabsCreateAllowedIpAddressRangesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, labs.BulkCreateAllowedIpAddressRangesRequest, ...labs.RequestEditorFn) (*labs.LabsCreateAllowedIpAddressRangesResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, labs.BulkCreateAllowedIpAddressRangesRequest, ...labs.RequestEditorFn) *labs.LabsCreateAllowedIpAddressRangesResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labs.LabsCreateAllowedIpAddressRangesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, labs.BulkCreateAllowedIpAddressRangesRequest, ...labs.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabsDeleteAlertsWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) LabsDeleteAlertsWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...labs.RequestEditorFn) (*labs.LabsDeleteAlertsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabsDeleteAlertsWithBodyWithResponse")
	}

	var r0 *labs.LabsDeleteAlertsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) (*labs.LabsDeleteAlertsResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) *labs.LabsDeleteAlertsResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labs.LabsDeleteAlertsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabsDeleteAlertsWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) LabsDeleteAlertsWithResponse(ctx context.Context, organizationId string, body labs.DeleteAlertsRequest, reqEditors ...labs.RequestEditorFn) (*labs.LabsDeleteAlertsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabsDeleteAlertsWithResponse")
	}

	var r0 *labs.LabsDeleteAlertsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, labs.DeleteAlertsRequest, ...labs.RequestEditorFn) (*labs.LabsDeleteAlertsResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, labs.DeleteAlertsRequest, ...labs.RequestEditorFn) *labs.LabsDeleteAlertsResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labs.LabsDeleteAlertsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, labs.DeleteAlertsRequest, ...labs.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabsDeleteAllowedIpAddressRangesWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) LabsDeleteAllowedIpAddressRangesWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...labs.RequestEditorFn) (*labs.LabsDeleteAllowedIpAddressRangesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabsDeleteAllowedIpAddressRangesWithBodyWithResponse")
	}

	var r0 *labs.LabsDeleteAllowedIpAddressRangesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) (*labs.LabsDeleteAllowedIpAddressRangesResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) *labs.LabsDeleteAllowedIpAddressRangesResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labs.LabsDeleteAllowedIpAddressRangesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabsDeleteAllowedIpAddressRangesWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) LabsDeleteAllowedIpAddressRangesWithResponse(ctx context.Context, organizationId string, body labs.BulkDeleteAllowedIpAddressRangesRequest, reqEditors ...labs.RequestEditorFn) (*labs.LabsDeleteAllowedIpAddressRangesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabsDeleteAllowedIpAddressRangesWithResponse")
	}

	var r0 *labs.LabsDeleteAllowedIpAddressRangesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, labs.BulkDeleteAllowedIpAddressRangesRequest, ...labs.RequestEditorFn) (*labs.LabsDeleteAllowedIpAddressRangesResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, labs.BulkDeleteAllowedIpAddressRangesRequest, ...labs.RequestEditorFn) *labs.LabsDeleteAllowedIpAddressRangesResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labs.LabsDeleteAllowedIpAddressRangesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, labs.BulkDeleteAllowedIpAddressRangesRequest, ...labs.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabsListAlertsWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) LabsListAlertsWithResponse(ctx context.Context, organizationId string, params *labs.LabsListAlertsParams, reqEditors ...labs.RequestEditorFn) (*labs.LabsListAlertsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabsListAlertsWithResponse")
	}

	var r0 *labs.LabsListAlertsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *labs.LabsListAlertsParams, ...labs.RequestEditorFn) (*labs.LabsListAlertsResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *labs.LabsListAlertsParams, ...labs.RequestEditorFn) *labs.LabsListAlertsResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labs.LabsListAlertsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *labs.LabsListAlertsParams, ...labs.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabsUpdateAlertsWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) LabsUpdateAlertsWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...labs.RequestEditorFn) (*labs.LabsUpdateAlertsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabsUpdateAlertsWithBodyWithResponse")
	}

	var r0 *labs.LabsUpdateAlertsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) (*labs.LabsUpdateAlertsResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) *labs.LabsUpdateAlertsResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labs.LabsUpdateAlertsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...labs.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabsUpdateAlertsWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) LabsUpdateAlertsWithResponse(ctx context.Context, organizationId string, body labs.UpdateAlertsRequest, reqEditors ...labs.RequestEditorFn) (*labs.LabsUpdateAlertsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabsUpdateAlertsWithResponse")
	}

	var r0 *labs.LabsUpdateAlertsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, labs.UpdateAlertsRequest, ...labs.RequestEditorFn) (*labs.LabsUpdateAlertsResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, labs.UpdateAlertsRequest, ...labs.RequestEditorFn) *labs.LabsUpdateAlertsResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labs.LabsUpdateAlertsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, labs.UpdateAlertsRequest, ...labs.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientWithResponsesInterface creates a new instance of ClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientWithResponsesInterface {
	mock := &ClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
