// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks_platform_v1

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	platform_v1 "github.com/astronomer/terraform-provider-astro/internal/clients/platform_v1"
)

// ClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type ClientWithResponsesInterface struct {
	mock.Mock
}

// CreateEnvironmentObjectWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...platform_v1.RequestEditorFn) (*platform_v1.CreateEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateEnvironmentObjectWithBodyWithResponse")
	}

	var r0 *platform_v1.CreateEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform_v1.RequestEditorFn) (*platform_v1.CreateEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...platform_v1.RequestEditorFn) *platform_v1.CreateEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform_v1.CreateEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...platform_v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateEnvironmentObjectWithResponse provides a mock function with given fields: ctx, organizationId, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateEnvironmentObjectWithResponse(ctx context.Context, organizationId string, body platform_v1.CreateEnvironmentObjectRequest, reqEditors ...platform_v1.RequestEditorFn) (*platform_v1.CreateEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateEnvironmentObjectWithResponse")
	}

	var r0 *platform_v1.CreateEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, platform_v1.CreateEnvironmentObjectRequest, ...platform_v1.RequestEditorFn) (*platform_v1.CreateEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, platform_v1.CreateEnvironmentObjectRequest, ...platform_v1.RequestEditorFn) *platform_v1.CreateEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform_v1.CreateEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, platform_v1.CreateEnvironmentObjectRequest, ...platform_v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEnvironmentObjectWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, reqEditors
func (_m *ClientWithResponsesInterface) DeleteEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...platform_v1.RequestEditorFn) (*platform_v1.DeleteEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEnvironmentObjectWithResponse")
	}

	var r0 *platform_v1.DeleteEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform_v1.RequestEditorFn) (*platform_v1.DeleteEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform_v1.RequestEditorFn) *platform_v1.DeleteEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform_v1.DeleteEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform_v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExcludeLinkingEnvironmentObjectWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) ExcludeLinkingEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...platform_v1.RequestEditorFn) (*platform_v1.ExcludeLinkingEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExcludeLinkingEnvironmentObjectWithBodyWithResponse")
	}

	var r0 *platform_v1.ExcludeLinkingEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform_v1.RequestEditorFn) (*platform_v1.ExcludeLinkingEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform_v1.RequestEditorFn) *platform_v1.ExcludeLinkingEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform_v1.ExcludeLinkingEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...platform_v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExcludeLinkingEnvironmentObjectWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, body, reqEditors
func (_m *ClientWithResponsesInterface) ExcludeLinkingEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, body platform_v1.ExcludeLinkEnvironmentObjectRequest, reqEditors ...platform_v1.RequestEditorFn) (*platform_v1.ExcludeLinkingEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExcludeLinkingEnvironmentObjectWithResponse")
	}

	var r0 *platform_v1.ExcludeLinkingEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform_v1.ExcludeLinkEnvironmentObjectRequest, ...platform_v1.RequestEditorFn) (*platform_v1.ExcludeLinkingEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform_v1.ExcludeLinkEnvironmentObjectRequest, ...platform_v1.RequestEditorFn) *platform_v1.ExcludeLinkingEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform_v1.ExcludeLinkingEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, platform_v1.ExcludeLinkEnvironmentObjectRequest, ...platform_v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEnvironmentObjectWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, reqEditors
func (_m *ClientWithResponsesInterface) GetEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...platform_v1.RequestEditorFn) (*platform_v1.GetEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetEnvironmentObjectWithResponse")
	}

	var r0 *platform_v1.GetEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform_v1.RequestEditorFn) (*platform_v1.GetEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...platform_v1.RequestEditorFn) *platform_v1.GetEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform_v1.GetEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...platform_v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEnvironmentObjectsWithResponse provides a mock function with given fields: ctx, organizationId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListEnvironmentObjectsWithResponse(ctx context.Context, organizationId string, params *platform_v1.ListEnvironmentObjectsParams, reqEditors ...platform_v1.RequestEditorFn) (*platform_v1.ListEnvironmentObjectsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListEnvironmentObjectsWithResponse")
	}

	var r0 *platform_v1.ListEnvironmentObjectsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform_v1.ListEnvironmentObjectsParams, ...platform_v1.RequestEditorFn) (*platform_v1.ListEnvironmentObjectsResponse, error)); ok {
		return rf(ctx, organizationId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *platform_v1.ListEnvironmentObjectsParams, ...platform_v1.RequestEditorFn) *platform_v1.ListEnvironmentObjectsResponse); ok {
		r0 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform_v1.ListEnvironmentObjectsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *platform_v1.ListEnvironmentObjectsParams, ...platform_v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEnvironmentObjectWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...platform_v1.RequestEditorFn) (*platform_v1.UpdateEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEnvironmentObjectWithBodyWithResponse")
	}

	var r0 *platform_v1.UpdateEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform_v1.RequestEditorFn) (*platform_v1.UpdateEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...platform_v1.RequestEditorFn) *platform_v1.UpdateEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform_v1.UpdateEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...platform_v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEnvironmentObjectWithResponse provides a mock function with given fields: ctx, organizationId, environmentObjectId, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, body platform_v1.UpdateEnvironmentObjectRequest, reqEditors ...platform_v1.RequestEditorFn) (*platform_v1.UpdateEnvironmentObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, environmentObjectId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEnvironmentObjectWithResponse")
	}

	var r0 *platform_v1.UpdateEnvironmentObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform_v1.UpdateEnvironmentObjectRequest, ...platform_v1.RequestEditorFn) (*platform_v1.UpdateEnvironmentObjectResponse, error)); ok {
		return rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, platform_v1.UpdateEnvironmentObjectRequest, ...platform_v1.RequestEditorFn) *platform_v1.UpdateEnvironmentObjectResponse); ok {
		r0 = rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platform_v1.UpdateEnvironmentObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, platform_v1.UpdateEnvironmentObjectRequest, ...platform_v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, environmentObjectId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientWithResponsesInterface creates a new instance of ClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientWithResponsesInterface {
	mock := &ClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
