// Package platform_v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package platform_v1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	JWTScopes = "JWT.Scopes"
)

// Defines values for BasicSubjectProfileSubjectType.
const (
	SERVICEKEY BasicSubjectProfileSubjectType = "SERVICEKEY"
	USER       BasicSubjectProfileSubjectType = "USER"
)

// Defines values for CreateEnvironmentObjectLinkRequestScope.
const (
	CreateEnvironmentObjectLinkRequestScopeDEPLOYMENT CreateEnvironmentObjectLinkRequestScope = "DEPLOYMENT"
)

// Defines values for CreateEnvironmentObjectMetricsExportOverridesRequestAuthType.
const (
	CreateEnvironmentObjectMetricsExportOverridesRequestAuthTypeAUTHTOKEN CreateEnvironmentObjectMetricsExportOverridesRequestAuthType = "AUTH_TOKEN"
	CreateEnvironmentObjectMetricsExportOverridesRequestAuthTypeBASIC     CreateEnvironmentObjectMetricsExportOverridesRequestAuthType = "BASIC"
	CreateEnvironmentObjectMetricsExportOverridesRequestAuthTypeSIGV4     CreateEnvironmentObjectMetricsExportOverridesRequestAuthType = "SIGV4"
)

// Defines values for CreateEnvironmentObjectMetricsExportOverridesRequestExporterType.
const (
	CreateEnvironmentObjectMetricsExportOverridesRequestExporterTypePROMETHEUS CreateEnvironmentObjectMetricsExportOverridesRequestExporterType = "PROMETHEUS"
)

// Defines values for CreateEnvironmentObjectMetricsExportRequestAuthType.
const (
	CreateEnvironmentObjectMetricsExportRequestAuthTypeAUTHTOKEN CreateEnvironmentObjectMetricsExportRequestAuthType = "AUTH_TOKEN"
	CreateEnvironmentObjectMetricsExportRequestAuthTypeBASIC     CreateEnvironmentObjectMetricsExportRequestAuthType = "BASIC"
	CreateEnvironmentObjectMetricsExportRequestAuthTypeSIGV4     CreateEnvironmentObjectMetricsExportRequestAuthType = "SIGV4"
)

// Defines values for CreateEnvironmentObjectMetricsExportRequestExporterType.
const (
	CreateEnvironmentObjectMetricsExportRequestExporterTypePROMETHEUS CreateEnvironmentObjectMetricsExportRequestExporterType = "PROMETHEUS"
)

// Defines values for CreateEnvironmentObjectRequestObjectType.
const (
	CreateEnvironmentObjectRequestObjectTypeAIRFLOWVARIABLE     CreateEnvironmentObjectRequestObjectType = "AIRFLOW_VARIABLE"
	CreateEnvironmentObjectRequestObjectTypeCONNECTION          CreateEnvironmentObjectRequestObjectType = "CONNECTION"
	CreateEnvironmentObjectRequestObjectTypeENVIRONMENTVARIABLE CreateEnvironmentObjectRequestObjectType = "ENVIRONMENT_VARIABLE"
	CreateEnvironmentObjectRequestObjectTypeMETRICSEXPORT       CreateEnvironmentObjectRequestObjectType = "METRICS_EXPORT"
)

// Defines values for CreateEnvironmentObjectRequestScope.
const (
	CreateEnvironmentObjectRequestScopeDEPLOYMENT CreateEnvironmentObjectRequestScope = "DEPLOYMENT"
	CreateEnvironmentObjectRequestScopeWORKSPACE  CreateEnvironmentObjectRequestScope = "WORKSPACE"
)

// Defines values for EnvironmentObjectObjectType.
const (
	EnvironmentObjectObjectTypeAIRFLOWVARIABLE     EnvironmentObjectObjectType = "AIRFLOW_VARIABLE"
	EnvironmentObjectObjectTypeCONNECTION          EnvironmentObjectObjectType = "CONNECTION"
	EnvironmentObjectObjectTypeENVIRONMENTVARIABLE EnvironmentObjectObjectType = "ENVIRONMENT_VARIABLE"
	EnvironmentObjectObjectTypeMETRICSEXPORT       EnvironmentObjectObjectType = "METRICS_EXPORT"
)

// Defines values for EnvironmentObjectScope.
const (
	EnvironmentObjectScopeDEPLOYMENT EnvironmentObjectScope = "DEPLOYMENT"
	EnvironmentObjectScopeWORKSPACE  EnvironmentObjectScope = "WORKSPACE"
)

// Defines values for EnvironmentObjectSourceScope.
const (
	EnvironmentObjectSourceScopeDEPLOYMENT EnvironmentObjectSourceScope = "DEPLOYMENT"
	EnvironmentObjectSourceScopeWORKSPACE  EnvironmentObjectSourceScope = "WORKSPACE"
)

// Defines values for EnvironmentObjectExcludeLinkScope.
const (
	EnvironmentObjectExcludeLinkScopeDEPLOYMENT EnvironmentObjectExcludeLinkScope = "DEPLOYMENT"
)

// Defines values for EnvironmentObjectLinkScope.
const (
	EnvironmentObjectLinkScopeDEPLOYMENT EnvironmentObjectLinkScope = "DEPLOYMENT"
)

// Defines values for EnvironmentObjectMetricsExportAuthType.
const (
	EnvironmentObjectMetricsExportAuthTypeAUTHTOKEN EnvironmentObjectMetricsExportAuthType = "AUTH_TOKEN"
	EnvironmentObjectMetricsExportAuthTypeBASIC     EnvironmentObjectMetricsExportAuthType = "BASIC"
	EnvironmentObjectMetricsExportAuthTypeSIGV4     EnvironmentObjectMetricsExportAuthType = "SIGV4"
)

// Defines values for EnvironmentObjectMetricsExportExporterType.
const (
	EnvironmentObjectMetricsExportExporterTypePROMETHEUS EnvironmentObjectMetricsExportExporterType = "PROMETHEUS"
)

// Defines values for EnvironmentObjectMetricsExportOverridesAuthType.
const (
	EnvironmentObjectMetricsExportOverridesAuthTypeAUTHTOKEN EnvironmentObjectMetricsExportOverridesAuthType = "AUTH_TOKEN"
	EnvironmentObjectMetricsExportOverridesAuthTypeBASIC     EnvironmentObjectMetricsExportOverridesAuthType = "BASIC"
	EnvironmentObjectMetricsExportOverridesAuthTypeSIGV4     EnvironmentObjectMetricsExportOverridesAuthType = "SIGV4"
)

// Defines values for EnvironmentObjectMetricsExportOverridesExporterType.
const (
	EnvironmentObjectMetricsExportOverridesExporterTypePROMETHEUS EnvironmentObjectMetricsExportOverridesExporterType = "PROMETHEUS"
)

// Defines values for ExcludeLinkEnvironmentObjectRequestScope.
const (
	ExcludeLinkEnvironmentObjectRequestScopeDEPLOYMENT ExcludeLinkEnvironmentObjectRequestScope = "DEPLOYMENT"
)

// Defines values for UpdateEnvironmentObjectLinkRequestScope.
const (
	UpdateEnvironmentObjectLinkRequestScopeDEPLOYMENT UpdateEnvironmentObjectLinkRequestScope = "DEPLOYMENT"
)

// Defines values for UpdateEnvironmentObjectMetricsExportOverridesRequestAuthType.
const (
	UpdateEnvironmentObjectMetricsExportOverridesRequestAuthTypeAUTHTOKEN UpdateEnvironmentObjectMetricsExportOverridesRequestAuthType = "AUTH_TOKEN"
	UpdateEnvironmentObjectMetricsExportOverridesRequestAuthTypeBASIC     UpdateEnvironmentObjectMetricsExportOverridesRequestAuthType = "BASIC"
	UpdateEnvironmentObjectMetricsExportOverridesRequestAuthTypeSIGV4     UpdateEnvironmentObjectMetricsExportOverridesRequestAuthType = "SIGV4"
)

// Defines values for UpdateEnvironmentObjectMetricsExportOverridesRequestExporterType.
const (
	UpdateEnvironmentObjectMetricsExportOverridesRequestExporterTypePROMETHEUS UpdateEnvironmentObjectMetricsExportOverridesRequestExporterType = "PROMETHEUS"
)

// Defines values for UpdateEnvironmentObjectMetricsExportRequestAuthType.
const (
	UpdateEnvironmentObjectMetricsExportRequestAuthTypeAUTHTOKEN UpdateEnvironmentObjectMetricsExportRequestAuthType = "AUTH_TOKEN"
	UpdateEnvironmentObjectMetricsExportRequestAuthTypeBASIC     UpdateEnvironmentObjectMetricsExportRequestAuthType = "BASIC"
	UpdateEnvironmentObjectMetricsExportRequestAuthTypeSIGV4     UpdateEnvironmentObjectMetricsExportRequestAuthType = "SIGV4"
)

// Defines values for UpdateEnvironmentObjectMetricsExportRequestExporterType.
const (
	UpdateEnvironmentObjectMetricsExportRequestExporterTypePROMETHEUS UpdateEnvironmentObjectMetricsExportRequestExporterType = "PROMETHEUS"
)

// Defines values for ListEnvironmentObjectsParamsSorts.
const (
	CreatedAtAsc   ListEnvironmentObjectsParamsSorts = "createdAt:asc"
	CreatedAtDesc  ListEnvironmentObjectsParamsSorts = "createdAt:desc"
	ObjectKeyAsc   ListEnvironmentObjectsParamsSorts = "objectKey:asc"
	ObjectKeyDesc  ListEnvironmentObjectsParamsSorts = "objectKey:desc"
	ObjectTypeAsc  ListEnvironmentObjectsParamsSorts = "objectType:asc"
	ObjectTypeDesc ListEnvironmentObjectsParamsSorts = "objectType:desc"
	UpdatedAtAsc   ListEnvironmentObjectsParamsSorts = "updatedAt:asc"
	UpdatedAtDesc  ListEnvironmentObjectsParamsSorts = "updatedAt:desc"
)

// Defines values for ListEnvironmentObjectsParamsObjectType.
const (
	AIRFLOWVARIABLE     ListEnvironmentObjectsParamsObjectType = "AIRFLOW_VARIABLE"
	CONNECTION          ListEnvironmentObjectsParamsObjectType = "CONNECTION"
	ENVIRONMENTVARIABLE ListEnvironmentObjectsParamsObjectType = "ENVIRONMENT_VARIABLE"
	METRICSEXPORT       ListEnvironmentObjectsParamsObjectType = "METRICS_EXPORT"
)

// BasicSubjectProfile defines model for BasicSubjectProfile.
type BasicSubjectProfile struct {
	// ApiTokenName The API token's name. Returned only when `SubjectType` is `SERVICEKEY`.
	ApiTokenName *string `json:"apiTokenName,omitempty"`

	// AvatarUrl The URL for the user's profile image. Returned only when `SubjectType` is `USER`.
	AvatarUrl *string `json:"avatarUrl,omitempty"`

	// FullName The subject's full name. Returned only when `SubjectType` is `USER`.
	FullName *string `json:"fullName,omitempty"`

	// Id The subject's ID.
	Id string `json:"id"`

	// SubjectType The subject type.
	SubjectType *BasicSubjectProfileSubjectType `json:"subjectType,omitempty"`

	// Username The subject's username. Returned only when `SubjectType` is `USER`.
	Username *string `json:"username,omitempty"`
}

// BasicSubjectProfileSubjectType The subject type.
type BasicSubjectProfileSubjectType string

// ConnectionAuthType defines model for ConnectionAuthType.
type ConnectionAuthType struct {
	// AirflowType The type of connection in Airflow
	AirflowType string `json:"airflowType"`

	// AuthMethodName The name of the auth method used in the connection
	AuthMethodName string `json:"authMethodName"`

	// Description A description of the connection auth type
	Description string `json:"description"`

	// GuidePath The URL to the guide for the connection auth type
	GuidePath *string `json:"guidePath,omitempty"`

	// Id The ID of the connection auth type
	Id string `json:"id"`

	// Name The name of the connection auth type
	Name string `json:"name"`

	// Parameters The parameters for the connection auth type
	Parameters []ConnectionAuthTypeParameter `json:"parameters"`

	// ProviderLogo The URL of the provider logo
	ProviderLogo *string `json:"providerLogo,omitempty"`

	// ProviderPackageName The name of the provider package
	ProviderPackageName string `json:"providerPackageName"`
}

// ConnectionAuthTypeParameter defines model for ConnectionAuthTypeParameter.
type ConnectionAuthTypeParameter struct {
	// AirflowParamName The name of the parameter in Airflow
	AirflowParamName string `json:"airflowParamName"`

	// DataType The data type of the parameter
	DataType string `json:"dataType"`

	// Description A description of the parameter
	Description string `json:"description"`

	// Example An example value for the parameter
	Example *string `json:"example,omitempty"`

	// FriendlyName The UI-friendly name for the parameter
	FriendlyName string `json:"friendlyName"`

	// IsInExtra Whether or not the parameter is included in the "extra" field
	IsInExtra bool `json:"isInExtra"`

	// IsRequired Whether the parameter is required
	IsRequired bool `json:"isRequired"`

	// IsSecret Whether the parameter is a secret
	IsSecret bool `json:"isSecret"`

	// Pattern A regex pattern for the parameter
	Pattern *string `json:"pattern,omitempty"`
}

// CreateEnvironmentObject defines model for CreateEnvironmentObject.
type CreateEnvironmentObject struct {
	// Id The ID of the environment object
	Id string `json:"id"`
}

// CreateEnvironmentObjectAirflowVariableOverridesRequest defines model for CreateEnvironmentObjectAirflowVariableOverridesRequest.
type CreateEnvironmentObjectAirflowVariableOverridesRequest struct {
	// Value The value of the Airflow variable
	Value *string `json:"value,omitempty"`
}

// CreateEnvironmentObjectAirflowVariableRequest defines model for CreateEnvironmentObjectAirflowVariableRequest.
type CreateEnvironmentObjectAirflowVariableRequest struct {
	// IsSecret Whether the value is a secret or not
	IsSecret *bool `json:"isSecret,omitempty"`

	// Value The value of the Airflow variable
	Value *string `json:"value,omitempty"`
}

// CreateEnvironmentObjectConnectionOverridesRequest defines model for CreateEnvironmentObjectConnectionOverridesRequest.
type CreateEnvironmentObjectConnectionOverridesRequest struct {
	// Extra Extra connection details, if any
	Extra *map[string]interface{} `json:"extra,omitempty"`

	// Host The host address for the connection
	Host *string `json:"host,omitempty"`

	// Login The username used for the connection
	Login *string `json:"login,omitempty"`

	// Password The password used for the connection
	Password *string `json:"password,omitempty"`

	// Port The port for the connection
	Port *int `json:"port,omitempty"`

	// Schema The schema for the connection
	Schema *string `json:"schema,omitempty"`

	// Type The type of connection
	Type *string `json:"type,omitempty"`
}

// CreateEnvironmentObjectConnectionRequest defines model for CreateEnvironmentObjectConnectionRequest.
type CreateEnvironmentObjectConnectionRequest struct {
	// AuthTypeId The ID for the connection auth type
	AuthTypeId *string `json:"authTypeId,omitempty"`

	// Extra Extra connection details, if any
	Extra *map[string]interface{} `json:"extra,omitempty"`

	// Host The host address for the connection
	Host *string `json:"host,omitempty"`

	// Login The username used for the connection
	Login *string `json:"login,omitempty"`

	// Password The password used for the connection
	Password *string `json:"password,omitempty"`

	// Port The port for the connection
	Port *int `json:"port,omitempty"`

	// Schema The schema for the connection
	Schema *string `json:"schema,omitempty"`

	// Type The type of connection
	Type string `json:"type"`
}

// CreateEnvironmentObjectEnvironmentVariableOverridesRequest defines model for CreateEnvironmentObjectEnvironmentVariableOverridesRequest.
type CreateEnvironmentObjectEnvironmentVariableOverridesRequest struct {
	// Value The value of the environment variable
	Value *string `json:"value,omitempty"`
}

// CreateEnvironmentObjectEnvironmentVariableRequest defines model for CreateEnvironmentObjectEnvironmentVariableRequest.
type CreateEnvironmentObjectEnvironmentVariableRequest struct {
	// IsSecret Whether the value is a secret or not
	IsSecret *bool `json:"isSecret,omitempty"`

	// Value The value of the environment variable
	Value *string `json:"value,omitempty"`
}

// CreateEnvironmentObjectLinkRequest defines model for CreateEnvironmentObjectLinkRequest.
type CreateEnvironmentObjectLinkRequest struct {
	Overrides *CreateEnvironmentObjectOverridesRequest `json:"overrides,omitempty"`

	// Scope Scope to link the environment object
	Scope CreateEnvironmentObjectLinkRequestScope `json:"scope"`

	// ScopeEntityId Entity ID of the scope to link the environment object
	ScopeEntityId string `json:"scopeEntityId"`
}

// CreateEnvironmentObjectLinkRequestScope Scope to link the environment object
type CreateEnvironmentObjectLinkRequestScope string

// CreateEnvironmentObjectMetricsExportOverridesRequest defines model for CreateEnvironmentObjectMetricsExportOverridesRequest.
type CreateEnvironmentObjectMetricsExportOverridesRequest struct {
	// AuthType The type of authentication to use when connecting to the remote endpoint
	AuthType *CreateEnvironmentObjectMetricsExportOverridesRequestAuthType `json:"authType,omitempty"`

	// BasicToken The bearer token to connect to the remote endpoint
	BasicToken *string `json:"basicToken,omitempty"`

	// Endpoint The Prometheus endpoint where the metrics are exported
	Endpoint *string `json:"endpoint,omitempty"`

	// ExporterType The type of exporter
	ExporterType *CreateEnvironmentObjectMetricsExportOverridesRequestExporterType `json:"exporterType,omitempty"`

	// Headers Add key-value pairs to the HTTP request headers made by Astro when connecting to the remote endpoint
	Headers *map[string]string `json:"headers,omitempty"`

	// Labels Any key-value pair metrics labels for your export. You can use these to filter your metrics in downstream applications.
	Labels *map[string]string `json:"labels,omitempty"`

	// Password The password to connect to the remote endpoint
	Password *string `json:"password,omitempty"`

	// SigV4AssumeArn The AWS IAM role ARN to assume for SigV4 authentication
	SigV4AssumeArn *string `json:"sigV4AssumeArn,omitempty"`

	// SigV4StsRegion The AWS STS region to use for SigV4 authentication
	SigV4StsRegion *string `json:"sigV4StsRegion,omitempty"`

	// Username The username to connect to the remote endpoint
	Username *string `json:"username,omitempty"`
}

// CreateEnvironmentObjectMetricsExportOverridesRequestAuthType The type of authentication to use when connecting to the remote endpoint
type CreateEnvironmentObjectMetricsExportOverridesRequestAuthType string

// CreateEnvironmentObjectMetricsExportOverridesRequestExporterType The type of exporter
type CreateEnvironmentObjectMetricsExportOverridesRequestExporterType string

// CreateEnvironmentObjectMetricsExportRequest defines model for CreateEnvironmentObjectMetricsExportRequest.
type CreateEnvironmentObjectMetricsExportRequest struct {
	// AuthType The type of authentication to use when connecting to the remote endpoint
	AuthType *CreateEnvironmentObjectMetricsExportRequestAuthType `json:"authType,omitempty"`

	// BasicToken The bearer token to connect to the remote endpoint
	BasicToken *string `json:"basicToken,omitempty"`

	// Endpoint The Prometheus endpoint where the metrics are exported
	Endpoint string `json:"endpoint"`

	// ExporterType The type of exporter
	ExporterType CreateEnvironmentObjectMetricsExportRequestExporterType `json:"exporterType"`

	// Headers Add key-value pairs to the HTTP request headers made by Astro when connecting to the remote endpoint
	Headers *map[string]string `json:"headers,omitempty"`

	// Labels Any key-value pair metrics labels for your export. You can use these to filter your metrics in downstream applications.
	Labels *map[string]string `json:"labels,omitempty"`

	// Password The password to connect to the remote endpoint
	Password *string `json:"password,omitempty"`

	// SigV4AssumeArn The AWS IAM role ARN to assume for SigV4 authentication
	SigV4AssumeArn *string `json:"sigV4AssumeArn,omitempty"`

	// SigV4StsRegion The AWS STS region to use for SigV4 authentication
	SigV4StsRegion *string `json:"sigV4StsRegion,omitempty"`

	// Username The username to connect to the remote endpoint
	Username *string `json:"username,omitempty"`
}

// CreateEnvironmentObjectMetricsExportRequestAuthType The type of authentication to use when connecting to the remote endpoint
type CreateEnvironmentObjectMetricsExportRequestAuthType string

// CreateEnvironmentObjectMetricsExportRequestExporterType The type of exporter
type CreateEnvironmentObjectMetricsExportRequestExporterType string

// CreateEnvironmentObjectOverridesRequest defines model for CreateEnvironmentObjectOverridesRequest.
type CreateEnvironmentObjectOverridesRequest struct {
	AirflowVariable     *CreateEnvironmentObjectAirflowVariableOverridesRequest     `json:"airflowVariable,omitempty"`
	Connection          *CreateEnvironmentObjectConnectionOverridesRequest          `json:"connection,omitempty"`
	EnvironmentVariable *CreateEnvironmentObjectEnvironmentVariableOverridesRequest `json:"environmentVariable,omitempty"`
	MetricsExport       *CreateEnvironmentObjectMetricsExportOverridesRequest       `json:"metricsExport,omitempty"`
}

// CreateEnvironmentObjectRequest defines model for CreateEnvironmentObjectRequest.
type CreateEnvironmentObjectRequest struct {
	AirflowVariable *CreateEnvironmentObjectAirflowVariableRequest `json:"airflowVariable,omitempty"`

	// AutoLinkDeployments Whether or not to automatically link Deployments to the environment object. Only applicable for WORKSPACE scope
	AutoLinkDeployments *bool                                     `json:"autoLinkDeployments,omitempty"`
	Connection          *CreateEnvironmentObjectConnectionRequest `json:"connection,omitempty"`

	// Description The description of the environment object
	Description         *string                                            `json:"description,omitempty"`
	EnvironmentVariable *CreateEnvironmentObjectEnvironmentVariableRequest `json:"environmentVariable,omitempty"`

	// ExcludeLinks The links to exclude from the environment object. Only applicable for WORKSPACE scope
	ExcludeLinks *[]ExcludeLinkEnvironmentObjectRequest `json:"excludeLinks,omitempty"`

	// Links The Deployments that Astro links to the environment object. Only applicable for WORKSPACE scope
	Links         *[]CreateEnvironmentObjectLinkRequest        `json:"links,omitempty"`
	MetricsExport *CreateEnvironmentObjectMetricsExportRequest `json:"metricsExport,omitempty"`

	// ObjectKey The key for the environment object
	ObjectKey string `json:"objectKey"`

	// ObjectType The type of environment object
	ObjectType CreateEnvironmentObjectRequestObjectType `json:"objectType"`

	// Scope The scope of the environment object
	Scope CreateEnvironmentObjectRequestScope `json:"scope"`

	// ScopeEntityId The ID of the scope entity where the environment object is created
	ScopeEntityId string `json:"scopeEntityId"`
}

// CreateEnvironmentObjectRequestObjectType The type of environment object
type CreateEnvironmentObjectRequestObjectType string

// CreateEnvironmentObjectRequestScope The scope of the environment object
type CreateEnvironmentObjectRequestScope string

// EnvironmentObject defines model for EnvironmentObject.
type EnvironmentObject struct {
	AirflowVariable *EnvironmentObjectAirflowVariable `json:"airflowVariable,omitempty"`

	// AutoLinkDeployments Whether or not to automatically link Deployments to the environment object
	AutoLinkDeployments *bool                        `json:"autoLinkDeployments,omitempty"`
	Connection          *EnvironmentObjectConnection `json:"connection,omitempty"`

	// CreatedAt The time when the environment object was created in UTC, formatted as `YYYY-MM-DDTHH:MM:SSZ`
	CreatedAt *string              `json:"createdAt,omitempty"`
	CreatedBy *BasicSubjectProfile `json:"createdBy,omitempty"`

	// Description The description of the environment object
	Description         *string                               `json:"description,omitempty"`
	EnvironmentVariable *EnvironmentObjectEnvironmentVariable `json:"environmentVariable,omitempty"`

	// ExcludeLinks The excluded links for the environment object
	ExcludeLinks *[]EnvironmentObjectExcludeLink `json:"excludeLinks,omitempty"`

	// Id The ID of the environment object
	Id *string `json:"id,omitempty"`

	// Links The Deployments linked to the environment object
	Links         *[]EnvironmentObjectLink        `json:"links,omitempty"`
	MetricsExport *EnvironmentObjectMetricsExport `json:"metricsExport,omitempty"`

	// ObjectKey The key for the environment object
	ObjectKey string `json:"objectKey"`

	// ObjectType The type of environment object
	ObjectType EnvironmentObjectObjectType `json:"objectType"`

	// Scope The scope of the environment object
	Scope EnvironmentObjectScope `json:"scope"`

	// ScopeEntityId The ID of the scope entity where the environment object is created
	ScopeEntityId string `json:"scopeEntityId"`

	// SetFields Names of fields that have a value set on the environment object. Secret values are masked in responses, so this list lets clients tell a set secret from an unset field. Map members appear as dotted paths (for example "extra.aws_secret")
	SetFields []string `json:"setFields"`

	// SourceScope The source scope of the environment object, if it is resolved from a link
	SourceScope *EnvironmentObjectSourceScope `json:"sourceScope,omitempty"`

	// SourceScopeEntityId The source scope entity ID of the environment object, if it is resolved from a link
	SourceScopeEntityId *string `json:"sourceScopeEntityId,omitempty"`

	// UpdatedAt The time when the environment object was updated in UTC, formatted as `YYYY-MM-DDTHH:MM:SSZ`
	UpdatedAt *string              `json:"updatedAt,omitempty"`
	UpdatedBy *BasicSubjectProfile `json:"updatedBy,omitempty"`
}

// EnvironmentObjectObjectType The type of environment object
type EnvironmentObjectObjectType string

// EnvironmentObjectScope The scope of the environment object
type EnvironmentObjectScope string

// EnvironmentObjectSourceScope The source scope of the environment object, if it is resolved from a link
type EnvironmentObjectSourceScope string

// EnvironmentObjectAirflowVariable defines model for EnvironmentObjectAirflowVariable.
type EnvironmentObjectAirflowVariable struct {
	// IsSecret Whether the value is a secret or not
	IsSecret bool `json:"isSecret"`

	// Value The value of the Airflow variable. If the value is a secret, the value returned is empty
	Value string `json:"value"`
}

// EnvironmentObjectAirflowVariableOverrides defines model for EnvironmentObjectAirflowVariableOverrides.
type EnvironmentObjectAirflowVariableOverrides struct {
	// Value The value of the Airflow variable
	Value string `json:"value"`
}

// EnvironmentObjectConnection defines model for EnvironmentObjectConnection.
type EnvironmentObjectConnection struct {
	ConnectionAuthType *ConnectionAuthType `json:"connectionAuthType,omitempty"`

	// Extra Extra connection details, if any
	Extra *map[string]interface{} `json:"extra,omitempty"`

	// Host The host address for the connection
	Host *string `json:"host,omitempty"`

	// Login The username used for the connection
	Login *string `json:"login,omitempty"`

	// Password The password used for the connection
	Password *string `json:"password,omitempty"`

	// Port The port for the connection
	Port *int `json:"port,omitempty"`

	// Schema The schema for the connection
	Schema *string `json:"schema,omitempty"`

	// Type The type of connection
	Type string `json:"type"`
}

// EnvironmentObjectConnectionOverrides defines model for EnvironmentObjectConnectionOverrides.
type EnvironmentObjectConnectionOverrides struct {
	// Extra Extra connection details, if any
	Extra *map[string]interface{} `json:"extra,omitempty"`

	// Host The host address for the connection
	Host *string `json:"host,omitempty"`

	// Login The username used for the connection
	Login *string `json:"login,omitempty"`

	// Password The password used for the connection
	Password *string `json:"password,omitempty"`

	// Port The port for the connection
	Port *int `json:"port,omitempty"`

	// Schema The schema for the connection
	Schema *string `json:"schema,omitempty"`

	// Type The type of connection
	Type *string `json:"type,omitempty"`
}

// EnvironmentObjectEnvironmentVariable defines model for EnvironmentObjectEnvironmentVariable.
type EnvironmentObjectEnvironmentVariable struct {
	// IsSecret Whether the value is a secret or not
	IsSecret bool `json:"isSecret"`

	// Value The value of the environment variable. If the value is a secret, the value returned is empty
	Value string `json:"value"`
}

// EnvironmentObjectEnvironmentVariableOverrides defines model for EnvironmentObjectEnvironmentVariableOverrides.
type EnvironmentObjectEnvironmentVariableOverrides struct {
	// Value The value of the environment variable
	Value string `json:"value"`
}

// EnvironmentObjectExcludeLink defines model for EnvironmentObjectExcludeLink.
type EnvironmentObjectExcludeLink struct {
	// Scope Scope of the excluded entity for environment object
	Scope EnvironmentObjectExcludeLinkScope `json:"scope"`

	// ScopeEntityId ID for the excluded entity for the environment object
	ScopeEntityId string `json:"scopeEntityId"`
}

// EnvironmentObjectExcludeLinkScope Scope of the excluded entity for environment object
type EnvironmentObjectExcludeLinkScope string

// EnvironmentObjectLink defines model for EnvironmentObjectLink.
type EnvironmentObjectLink struct {
	AirflowVariableOverrides     *EnvironmentObjectAirflowVariableOverrides     `json:"airflowVariableOverrides,omitempty"`
	ConnectionOverrides          *EnvironmentObjectConnectionOverrides          `json:"connectionOverrides,omitempty"`
	EnvironmentVariableOverrides *EnvironmentObjectEnvironmentVariableOverrides `json:"environmentVariableOverrides,omitempty"`
	MetricsExportOverrides       *EnvironmentObjectMetricsExportOverrides       `json:"metricsExportOverrides,omitempty"`

	// Scope Scope of the linked entity for the environment object
	Scope EnvironmentObjectLinkScope `json:"scope"`

	// ScopeEntityId Linked entity ID the environment object
	ScopeEntityId string `json:"scopeEntityId"`

	// SetFields Names of override fields that have a value set on this link. Secret values are masked, so this list distinguishes a set secret override from an unset one. Map members appear as dotted paths (for example "headers.X-Key")
	SetFields []string `json:"setFields"`
}

// EnvironmentObjectLinkScope Scope of the linked entity for the environment object
type EnvironmentObjectLinkScope string

// EnvironmentObjectMetricsExport defines model for EnvironmentObjectMetricsExport.
type EnvironmentObjectMetricsExport struct {
	// AuthType The type of authentication to use when connecting to the remote endpoint
	AuthType *EnvironmentObjectMetricsExportAuthType `json:"authType,omitempty"`

	// BasicToken The bearer token to connect to the remote endpoint
	BasicToken *string `json:"basicToken,omitempty"`

	// Endpoint The Prometheus endpoint where the metrics are exported
	Endpoint string `json:"endpoint"`

	// ExporterType The type of exporter
	ExporterType EnvironmentObjectMetricsExportExporterType `json:"exporterType"`

	// Headers Add key-value pairs to the HTTP request headers made by Astro when connecting to the remote endpoint
	Headers *map[string]string `json:"headers,omitempty"`

	// Labels Any key-value pair metrics labels for your export. You can use these to filter your metrics in downstream applications.
	Labels *map[string]string `json:"labels,omitempty"`

	// Password The password to connect to the remote endpoint
	Password *string `json:"password,omitempty"`

	// SigV4AssumeArn The AWS IAM role ARN to assume for SigV4 authentication
	SigV4AssumeArn *string `json:"sigV4AssumeArn,omitempty"`

	// SigV4StsRegion The AWS STS region to use for SigV4 authentication
	SigV4StsRegion *string `json:"sigV4StsRegion,omitempty"`

	// Username The username to connect to the remote endpoint
	Username *string `json:"username,omitempty"`
}

// EnvironmentObjectMetricsExportAuthType The type of authentication to use when connecting to the remote endpoint
type EnvironmentObjectMetricsExportAuthType string

// EnvironmentObjectMetricsExportExporterType The type of exporter
type EnvironmentObjectMetricsExportExporterType string

// EnvironmentObjectMetricsExportOverrides defines model for EnvironmentObjectMetricsExportOverrides.
type EnvironmentObjectMetricsExportOverrides struct {
	// AuthType The type of authentication to use when connecting to the remote endpoint
	AuthType *EnvironmentObjectMetricsExportOverridesAuthType `json:"authType,omitempty"`

	// BasicToken The bearer token to connect to the remote endpoint
	BasicToken *string `json:"basicToken,omitempty"`

	// Endpoint The Prometheus endpoint where the metrics are exported
	Endpoint *string `json:"endpoint,omitempty"`

	// ExporterType The type of exporter
	ExporterType *EnvironmentObjectMetricsExportOverridesExporterType `json:"exporterType,omitempty"`

	// Headers Add key-value pairs to the HTTP request headers made by Astro when connecting to the remote endpoint
	Headers *map[string]string `json:"headers,omitempty"`

	// Labels Any key-value pair metrics labels for your export. You can use these to filter your metrics in downstream applications.
	Labels *map[string]string `json:"labels,omitempty"`

	// Password The password to connect to the remote endpoint
	Password *string `json:"password,omitempty"`

	// SigV4AssumeArn The AWS IAM role ARN to assume for SigV4 authentication
	SigV4AssumeArn *string `json:"sigV4AssumeArn,omitempty"`

	// SigV4StsRegion The AWS STS region to use for SigV4 authentication
	SigV4StsRegion *string `json:"sigV4StsRegion,omitempty"`

	// Username The username to connect to the remote endpoint
	Username *string `json:"username,omitempty"`
}

// EnvironmentObjectMetricsExportOverridesAuthType The type of authentication to use when connecting to the remote endpoint
type EnvironmentObjectMetricsExportOverridesAuthType string

// EnvironmentObjectMetricsExportOverridesExporterType The type of exporter
type EnvironmentObjectMetricsExportOverridesExporterType string

// EnvironmentObjectsPaginated defines model for EnvironmentObjectsPaginated.
type EnvironmentObjectsPaginated struct {
	// EnvironmentObjects The list of environment objects
	EnvironmentObjects []EnvironmentObject `json:"environmentObjects"`

	// Limit The maximum number of environment objects in current page
	Limit int `json:"limit"`

	// Offset The offset of the current page of environment objects
	Offset int `json:"offset"`

	// TotalCount The total number of environment objects
	TotalCount int `json:"totalCount"`
}

// Error defines model for Error.
type Error struct {
	// FieldErrors FieldErrors carries one entry per failed request-validation constraint.
	// Only present on 400 responses caused by request binding/validation.
	FieldErrors *[]FieldValidationError `json:"fieldErrors,omitempty"`
	Message     string                  `json:"message"`
	RequestId   string                  `json:"requestId"`
	StatusCode  int                     `json:"statusCode"`
}

// ExcludeLinkEnvironmentObjectRequest defines model for ExcludeLinkEnvironmentObjectRequest.
type ExcludeLinkEnvironmentObjectRequest struct {
	// Scope Scope of the entity to exclude for environment object
	Scope ExcludeLinkEnvironmentObjectRequestScope `json:"scope"`

	// ScopeEntityId Entity ID to exclude for the environment object
	ScopeEntityId string `json:"scopeEntityId"`
}

// ExcludeLinkEnvironmentObjectRequestScope Scope of the entity to exclude for environment object
type ExcludeLinkEnvironmentObjectRequestScope string

// FieldValidationError defines model for FieldValidationError.
type FieldValidationError struct {
	Code    string `json:"code"`
	Field   string `json:"field"`
	Message string `json:"message"`
}

// UpdateEnvironmentObjectAirflowVariableOverridesRequest defines model for UpdateEnvironmentObjectAirflowVariableOverridesRequest.
type UpdateEnvironmentObjectAirflowVariableOverridesRequest struct {
	// Value The value of the Airflow variable
	Value *string `json:"value,omitempty"`
}

// UpdateEnvironmentObjectAirflowVariableRequest defines model for UpdateEnvironmentObjectAirflowVariableRequest.
type UpdateEnvironmentObjectAirflowVariableRequest struct {
	// Value The value of the Airflow variable
	Value *string `json:"value,omitempty"`
}

// UpdateEnvironmentObjectConnectionOverridesRequest defines model for UpdateEnvironmentObjectConnectionOverridesRequest.
type UpdateEnvironmentObjectConnectionOverridesRequest struct {
	// Extra Extra connection details, if any
	Extra *map[string]interface{} `json:"extra,omitempty"`

	// Host The host address for the connection
	Host *string `json:"host,omitempty"`

	// Login The username used for the connection
	Login *string `json:"login,omitempty"`

	// Password The password used for the connection
	Password *string `json:"password,omitempty"`

	// Port The port for the connection
	Port *int `json:"port,omitempty"`

	// Schema The schema for the connection
	Schema *string `json:"schema,omitempty"`

	// Type The type of connection
	Type *string `json:"type,omitempty"`
}

// UpdateEnvironmentObjectConnectionRequest defines model for UpdateEnvironmentObjectConnectionRequest.
type UpdateEnvironmentObjectConnectionRequest struct {
	// AuthTypeId The ID for the connection auth type
	AuthTypeId *string `json:"authTypeId,omitempty"`

	// Extra Extra connection details, if any
	Extra *map[string]interface{} `json:"extra,omitempty"`

	// Host The host address for the connection
	Host *string `json:"host,omitempty"`

	// Login The username used for the connection
	Login *string `json:"login,omitempty"`

	// Password The password used for the connection
	Password *string `json:"password,omitempty"`

	// Port The port for the connection
	Port *int `json:"port,omitempty"`

	// Schema The schema for the connection
	Schema *string `json:"schema,omitempty"`

	// Type The type of connection
	Type string `json:"type"`
}

// UpdateEnvironmentObjectEnvironmentVariableOverridesRequest defines model for UpdateEnvironmentObjectEnvironmentVariableOverridesRequest.
type UpdateEnvironmentObjectEnvironmentVariableOverridesRequest struct {
	// Value The value of the environment variable
	Value *string `json:"value,omitempty"`
}

// UpdateEnvironmentObjectEnvironmentVariableRequest defines model for UpdateEnvironmentObjectEnvironmentVariableRequest.
type UpdateEnvironmentObjectEnvironmentVariableRequest struct {
	// Value The value of the environment variable
	Value *string `json:"value,omitempty"`
}

// UpdateEnvironmentObjectLinkRequest defines model for UpdateEnvironmentObjectLinkRequest.
type UpdateEnvironmentObjectLinkRequest struct {
	Overrides *UpdateEnvironmentObjectOverridesRequest `json:"overrides,omitempty"`

	// Scope Scope of the entity to link the environment object
	Scope UpdateEnvironmentObjectLinkRequestScope `json:"scope"`

	// ScopeEntityId Entity ID to link the environment object
	ScopeEntityId string `json:"scopeEntityId"`
}

// UpdateEnvironmentObjectLinkRequestScope Scope of the entity to link the environment object
type UpdateEnvironmentObjectLinkRequestScope string

// UpdateEnvironmentObjectMetricsExportOverridesRequest defines model for UpdateEnvironmentObjectMetricsExportOverridesRequest.
type UpdateEnvironmentObjectMetricsExportOverridesRequest struct {
	// AuthType The type of authentication to use when connecting to the remote endpoint
	AuthType *UpdateEnvironmentObjectMetricsExportOverridesRequestAuthType `json:"authType,omitempty"`

	// BasicToken The bearer token to connect to the remote endpoint
	BasicToken *string `json:"basicToken,omitempty"`

	// Endpoint The Prometheus endpoint where the metrics are exported
	Endpoint *string `json:"endpoint,omitempty"`

	// ExporterType The type of exporter
	ExporterType *UpdateEnvironmentObjectMetricsExportOverridesRequestExporterType `json:"exporterType,omitempty"`

	// Headers Add key-value pairs to the HTTP request headers made by Astro when connecting to the remote endpoint
	Headers *map[string]string `json:"headers,omitempty"`

	// Labels Any key-value pair metrics labels for your export. You can use these to filter your metrics in downstream applications.
	Labels *map[string]string `json:"labels,omitempty"`

	// Password The password to connect to the remote endpoint
	Password *string `json:"password,omitempty"`

	// SigV4AssumeArn The AWS IAM role ARN to assume for SigV4 authentication
	SigV4AssumeArn *string `json:"sigV4AssumeArn,omitempty"`

	// SigV4StsRegion The AWS STS region to use for SigV4 authentication
	SigV4StsRegion *string `json:"sigV4StsRegion,omitempty"`

	// Username The username to connect to the remote endpoint
	Username *string `json:"username,omitempty"`
}

// UpdateEnvironmentObjectMetricsExportOverridesRequestAuthType The type of authentication to use when connecting to the remote endpoint
type UpdateEnvironmentObjectMetricsExportOverridesRequestAuthType string

// UpdateEnvironmentObjectMetricsExportOverridesRequestExporterType The type of exporter
type UpdateEnvironmentObjectMetricsExportOverridesRequestExporterType string

// UpdateEnvironmentObjectMetricsExportRequest defines model for UpdateEnvironmentObjectMetricsExportRequest.
type UpdateEnvironmentObjectMetricsExportRequest struct {
	// AuthType The type of authentication to use when connecting to the remote endpoint
	AuthType *UpdateEnvironmentObjectMetricsExportRequestAuthType `json:"authType,omitempty"`

	// BasicToken The bearer token to connect to the remote endpoint
	BasicToken *string `json:"basicToken,omitempty"`

	// Endpoint The Prometheus endpoint where the metrics are exported
	Endpoint *string `json:"endpoint,omitempty"`

	// ExporterType The type of exporter
	ExporterType *UpdateEnvironmentObjectMetricsExportRequestExporterType `json:"exporterType,omitempty"`

	// Headers Add key-value pairs to the HTTP request headers made by Astro when connecting to the remote endpoint
	Headers *map[string]string `json:"headers,omitempty"`

	// Labels Any key-value pair metrics labels for your export. You can use these to filter your metrics in downstream applications.
	Labels *map[string]string `json:"labels,omitempty"`

	// Password The password to connect to the remote endpoint
	Password *string `json:"password,omitempty"`

	// SigV4AssumeArn The AWS IAM role ARN to assume for SigV4 authentication
	SigV4AssumeArn *string `json:"sigV4AssumeArn,omitempty"`

	// SigV4StsRegion The AWS STS region to use for SigV4 authentication
	SigV4StsRegion *string `json:"sigV4StsRegion,omitempty"`

	// Username The username to connect to the remote endpoint
	Username *string `json:"username,omitempty"`
}

// UpdateEnvironmentObjectMetricsExportRequestAuthType The type of authentication to use when connecting to the remote endpoint
type UpdateEnvironmentObjectMetricsExportRequestAuthType string

// UpdateEnvironmentObjectMetricsExportRequestExporterType The type of exporter
type UpdateEnvironmentObjectMetricsExportRequestExporterType string

// UpdateEnvironmentObjectOverridesRequest defines model for UpdateEnvironmentObjectOverridesRequest.
type UpdateEnvironmentObjectOverridesRequest struct {
	AirflowVariable     *UpdateEnvironmentObjectAirflowVariableOverridesRequest     `json:"airflowVariable,omitempty"`
	Connection          *UpdateEnvironmentObjectConnectionOverridesRequest          `json:"connection,omitempty"`
	EnvironmentVariable *UpdateEnvironmentObjectEnvironmentVariableOverridesRequest `json:"environmentVariable,omitempty"`
	MetricsExport       *UpdateEnvironmentObjectMetricsExportOverridesRequest       `json:"metricsExport,omitempty"`

	// UnsetFields Names of override fields to unset on the linked entity so it inherits the parent value. For connections and metrics exports, individual fields are named (for example "password"); for map fields a single key can be unset with a dotted path (for example "extra.aws_secret"). A field cannot be both set above and listed here.
	UnsetFields *[]string `json:"unsetFields,omitempty"`
}

// UpdateEnvironmentObjectRequest defines model for UpdateEnvironmentObjectRequest.
type UpdateEnvironmentObjectRequest struct {
	AirflowVariable *UpdateEnvironmentObjectAirflowVariableRequest `json:"airflowVariable,omitempty"`

	// AutoLinkDeployments Whether or not to automatically link Deployments to the environment object. Only applicable for WORKSPACE scope
	AutoLinkDeployments *bool                                     `json:"autoLinkDeployments,omitempty"`
	Connection          *UpdateEnvironmentObjectConnectionRequest `json:"connection,omitempty"`

	// Description The description of the environment object
	Description         *string                                            `json:"description,omitempty"`
	EnvironmentVariable *UpdateEnvironmentObjectEnvironmentVariableRequest `json:"environmentVariable,omitempty"`

	// ExcludeLinks The links to exclude from the environment object. Only applicable for WORKSPACE scope
	ExcludeLinks *[]ExcludeLinkEnvironmentObjectRequest `json:"excludeLinks,omitempty"`

	// Links The Deployments that Astro links to the environment object. Only applicable for WORKSPACE scope
	Links         *[]UpdateEnvironmentObjectLinkRequest        `json:"links,omitempty"`
	MetricsExport *UpdateEnvironmentObjectMetricsExportRequest `json:"metricsExport,omitempty"`
}

// ListEnvironmentObjectsParams defines parameters for ListEnvironmentObjects.
type ListEnvironmentObjectsParams struct {
	// Offset The number of results to skip before returning values.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The maximum number of results to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Sorts A list of field names to sort by, and whether to show results as ascending or descending. Formatted as `<fieldName>:asc` or `<fieldName>:desc`.
	Sorts *[]ListEnvironmentObjectsParamsSorts `form:"sorts,omitempty" json:"sorts,omitempty"`

	// WorkspaceId The Workspace ID to filter for. The API returns details for all environment objects belonging only to this specified Workspace.
	WorkspaceId *string `form:"workspaceId,omitempty" json:"workspaceId,omitempty"`

	// DeploymentId The Deployment ID to filter for. The API returns details for all environment objects belonging only to this specified Deployment.
	DeploymentId *string `form:"deploymentId,omitempty" json:"deploymentId,omitempty"`

	// ObjectType The environment object type to filter for. The API returns details for all environment objects belonging only to this specified object type.
	ObjectType *ListEnvironmentObjectsParamsObjectType `form:"objectType,omitempty" json:"objectType,omitempty"`

	// ObjectKey The environment object key to filter for. The API returns details for all environment objects belonging only to the specified object key.
	ObjectKey *string `form:"objectKey,omitempty" json:"objectKey,omitempty"`

	// ShowSecrets If true, returns the actual values of fields of type secret in the API response.
	ShowSecrets *bool `form:"showSecrets,omitempty" json:"showSecrets,omitempty"`

	// ResolveLinked Resolve and return the environment objects linked to the specified Deployment or Workspace in the API response.
	ResolveLinked *bool `form:"resolveLinked,omitempty" json:"resolveLinked,omitempty"`
}

// ListEnvironmentObjectsParamsSorts defines parameters for ListEnvironmentObjects.
type ListEnvironmentObjectsParamsSorts string

// ListEnvironmentObjectsParamsObjectType defines parameters for ListEnvironmentObjects.
type ListEnvironmentObjectsParamsObjectType string

// CreateEnvironmentObjectJSONRequestBody defines body for CreateEnvironmentObject for application/json ContentType.
type CreateEnvironmentObjectJSONRequestBody = CreateEnvironmentObjectRequest

// UpdateEnvironmentObjectJSONRequestBody defines body for UpdateEnvironmentObject for application/json ContentType.
type UpdateEnvironmentObjectJSONRequestBody = UpdateEnvironmentObjectRequest

// ExcludeLinkingEnvironmentObjectJSONRequestBody defines body for ExcludeLinkingEnvironmentObject for application/json ContentType.
type ExcludeLinkingEnvironmentObjectJSONRequestBody = ExcludeLinkEnvironmentObjectRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListEnvironmentObjects request
	ListEnvironmentObjects(ctx context.Context, organizationId string, params *ListEnvironmentObjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateEnvironmentObjectWithBody request with any body
	CreateEnvironmentObjectWithBody(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateEnvironmentObject(ctx context.Context, organizationId string, body CreateEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteEnvironmentObject request
	DeleteEnvironmentObject(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEnvironmentObject request
	GetEnvironmentObject(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateEnvironmentObjectWithBody request with any body
	UpdateEnvironmentObjectWithBody(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateEnvironmentObject(ctx context.Context, organizationId string, environmentObjectId string, body UpdateEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExcludeLinkingEnvironmentObjectWithBody request with any body
	ExcludeLinkingEnvironmentObjectWithBody(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExcludeLinkingEnvironmentObject(ctx context.Context, organizationId string, environmentObjectId string, body ExcludeLinkingEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListEnvironmentObjects(ctx context.Context, organizationId string, params *ListEnvironmentObjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEnvironmentObjectsRequest(c.Server, organizationId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateEnvironmentObjectWithBody(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEnvironmentObjectRequestWithBody(c.Server, organizationId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateEnvironmentObject(ctx context.Context, organizationId string, body CreateEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEnvironmentObjectRequest(c.Server, organizationId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteEnvironmentObject(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteEnvironmentObjectRequest(c.Server, organizationId, environmentObjectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEnvironmentObject(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEnvironmentObjectRequest(c.Server, organizationId, environmentObjectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateEnvironmentObjectWithBody(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateEnvironmentObjectRequestWithBody(c.Server, organizationId, environmentObjectId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateEnvironmentObject(ctx context.Context, organizationId string, environmentObjectId string, body UpdateEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateEnvironmentObjectRequest(c.Server, organizationId, environmentObjectId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExcludeLinkingEnvironmentObjectWithBody(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExcludeLinkingEnvironmentObjectRequestWithBody(c.Server, organizationId, environmentObjectId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExcludeLinkingEnvironmentObject(ctx context.Context, organizationId string, environmentObjectId string, body ExcludeLinkingEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExcludeLinkingEnvironmentObjectRequest(c.Server, organizationId, environmentObjectId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListEnvironmentObjectsRequest generates requests for ListEnvironmentObjects
func NewListEnvironmentObjectsRequest(server string, organizationId string, params *ListEnvironmentObjectsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environment-objects", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sorts != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sorts", runtime.ParamLocationQuery, *params.Sorts); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.WorkspaceId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "workspaceId", runtime.ParamLocationQuery, *params.WorkspaceId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DeploymentId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "deploymentId", runtime.ParamLocationQuery, *params.DeploymentId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ObjectType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "objectType", runtime.ParamLocationQuery, *params.ObjectType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ObjectKey != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "objectKey", runtime.ParamLocationQuery, *params.ObjectKey); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ShowSecrets != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "showSecrets", runtime.ParamLocationQuery, *params.ShowSecrets); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ResolveLinked != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "resolveLinked", runtime.ParamLocationQuery, *params.ResolveLinked); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateEnvironmentObjectRequest calls the generic CreateEnvironmentObject builder with application/json body
func NewCreateEnvironmentObjectRequest(server string, organizationId string, body CreateEnvironmentObjectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateEnvironmentObjectRequestWithBody(server, organizationId, "application/json", bodyReader)
}

// NewCreateEnvironmentObjectRequestWithBody generates requests for CreateEnvironmentObject with any type of body
func NewCreateEnvironmentObjectRequestWithBody(server string, organizationId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environment-objects", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteEnvironmentObjectRequest generates requests for DeleteEnvironmentObject
func NewDeleteEnvironmentObjectRequest(server string, organizationId string, environmentObjectId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "environmentObjectId", runtime.ParamLocationPath, environmentObjectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environment-objects/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEnvironmentObjectRequest generates requests for GetEnvironmentObject
func NewGetEnvironmentObjectRequest(server string, organizationId string, environmentObjectId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "environmentObjectId", runtime.ParamLocationPath, environmentObjectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environment-objects/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateEnvironmentObjectRequest calls the generic UpdateEnvironmentObject builder with application/json body
func NewUpdateEnvironmentObjectRequest(server string, organizationId string, environmentObjectId string, body UpdateEnvironmentObjectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateEnvironmentObjectRequestWithBody(server, organizationId, environmentObjectId, "application/json", bodyReader)
}

// NewUpdateEnvironmentObjectRequestWithBody generates requests for UpdateEnvironmentObject with any type of body
func NewUpdateEnvironmentObjectRequestWithBody(server string, organizationId string, environmentObjectId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "environmentObjectId", runtime.ParamLocationPath, environmentObjectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environment-objects/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewExcludeLinkingEnvironmentObjectRequest calls the generic ExcludeLinkingEnvironmentObject builder with application/json body
func NewExcludeLinkingEnvironmentObjectRequest(server string, organizationId string, environmentObjectId string, body ExcludeLinkingEnvironmentObjectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExcludeLinkingEnvironmentObjectRequestWithBody(server, organizationId, environmentObjectId, "application/json", bodyReader)
}

// NewExcludeLinkingEnvironmentObjectRequestWithBody generates requests for ExcludeLinkingEnvironmentObject with any type of body
func NewExcludeLinkingEnvironmentObjectRequestWithBody(server string, organizationId string, environmentObjectId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "environmentObjectId", runtime.ParamLocationPath, environmentObjectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environment-objects/%s/exclude-linking", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListEnvironmentObjectsWithResponse request
	ListEnvironmentObjectsWithResponse(ctx context.Context, organizationId string, params *ListEnvironmentObjectsParams, reqEditors ...RequestEditorFn) (*ListEnvironmentObjectsResponse, error)

	// CreateEnvironmentObjectWithBodyWithResponse request with any body
	CreateEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEnvironmentObjectResponse, error)

	CreateEnvironmentObjectWithResponse(ctx context.Context, organizationId string, body CreateEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEnvironmentObjectResponse, error)

	// DeleteEnvironmentObjectWithResponse request
	DeleteEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...RequestEditorFn) (*DeleteEnvironmentObjectResponse, error)

	// GetEnvironmentObjectWithResponse request
	GetEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...RequestEditorFn) (*GetEnvironmentObjectResponse, error)

	// UpdateEnvironmentObjectWithBodyWithResponse request with any body
	UpdateEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateEnvironmentObjectResponse, error)

	UpdateEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, body UpdateEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateEnvironmentObjectResponse, error)

	// ExcludeLinkingEnvironmentObjectWithBodyWithResponse request with any body
	ExcludeLinkingEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExcludeLinkingEnvironmentObjectResponse, error)

	ExcludeLinkingEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, body ExcludeLinkingEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*ExcludeLinkingEnvironmentObjectResponse, error)
}

type ListEnvironmentObjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvironmentObjectsPaginated
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSON405      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListEnvironmentObjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListEnvironmentObjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateEnvironmentObjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateEnvironmentObject
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSON405      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r CreateEnvironmentObjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateEnvironmentObjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteEnvironmentObjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSON405      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r DeleteEnvironmentObjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteEnvironmentObjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEnvironmentObjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvironmentObject
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSON405      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetEnvironmentObjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEnvironmentObjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateEnvironmentObjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvironmentObject
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSON405      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r UpdateEnvironmentObjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateEnvironmentObjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ExcludeLinkingEnvironmentObjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSON405      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ExcludeLinkingEnvironmentObjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExcludeLinkingEnvironmentObjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListEnvironmentObjectsWithResponse request returning *ListEnvironmentObjectsResponse
func (c *ClientWithResponses) ListEnvironmentObjectsWithResponse(ctx context.Context, organizationId string, params *ListEnvironmentObjectsParams, reqEditors ...RequestEditorFn) (*ListEnvironmentObjectsResponse, error) {
	rsp, err := c.ListEnvironmentObjects(ctx, organizationId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListEnvironmentObjectsResponse(rsp)
}

// CreateEnvironmentObjectWithBodyWithResponse request with arbitrary body returning *CreateEnvironmentObjectResponse
func (c *ClientWithResponses) CreateEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEnvironmentObjectResponse, error) {
	rsp, err := c.CreateEnvironmentObjectWithBody(ctx, organizationId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEnvironmentObjectResponse(rsp)
}

func (c *ClientWithResponses) CreateEnvironmentObjectWithResponse(ctx context.Context, organizationId string, body CreateEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEnvironmentObjectResponse, error) {
	rsp, err := c.CreateEnvironmentObject(ctx, organizationId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEnvironmentObjectResponse(rsp)
}

// DeleteEnvironmentObjectWithResponse request returning *DeleteEnvironmentObjectResponse
func (c *ClientWithResponses) DeleteEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...RequestEditorFn) (*DeleteEnvironmentObjectResponse, error) {
	rsp, err := c.DeleteEnvironmentObject(ctx, organizationId, environmentObjectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteEnvironmentObjectResponse(rsp)
}

// GetEnvironmentObjectWithResponse request returning *GetEnvironmentObjectResponse
func (c *ClientWithResponses) GetEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, reqEditors ...RequestEditorFn) (*GetEnvironmentObjectResponse, error) {
	rsp, err := c.GetEnvironmentObject(ctx, organizationId, environmentObjectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEnvironmentObjectResponse(rsp)
}

// UpdateEnvironmentObjectWithBodyWithResponse request with arbitrary body returning *UpdateEnvironmentObjectResponse
func (c *ClientWithResponses) UpdateEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateEnvironmentObjectResponse, error) {
	rsp, err := c.UpdateEnvironmentObjectWithBody(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateEnvironmentObjectResponse(rsp)
}

func (c *ClientWithResponses) UpdateEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, body UpdateEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateEnvironmentObjectResponse, error) {
	rsp, err := c.UpdateEnvironmentObject(ctx, organizationId, environmentObjectId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateEnvironmentObjectResponse(rsp)
}

// ExcludeLinkingEnvironmentObjectWithBodyWithResponse request with arbitrary body returning *ExcludeLinkingEnvironmentObjectResponse
func (c *ClientWithResponses) ExcludeLinkingEnvironmentObjectWithBodyWithResponse(ctx context.Context, organizationId string, environmentObjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExcludeLinkingEnvironmentObjectResponse, error) {
	rsp, err := c.ExcludeLinkingEnvironmentObjectWithBody(ctx, organizationId, environmentObjectId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExcludeLinkingEnvironmentObjectResponse(rsp)
}

func (c *ClientWithResponses) ExcludeLinkingEnvironmentObjectWithResponse(ctx context.Context, organizationId string, environmentObjectId string, body ExcludeLinkingEnvironmentObjectJSONRequestBody, reqEditors ...RequestEditorFn) (*ExcludeLinkingEnvironmentObjectResponse, error) {
	rsp, err := c.ExcludeLinkingEnvironmentObject(ctx, organizationId, environmentObjectId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExcludeLinkingEnvironmentObjectResponse(rsp)
}

// ParseListEnvironmentObjectsResponse parses an HTTP response from a ListEnvironmentObjectsWithResponse call
func ParseListEnvironmentObjectsResponse(rsp *http.Response) (*ListEnvironmentObjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListEnvironmentObjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvironmentObjectsPaginated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateEnvironmentObjectResponse parses an HTTP response from a CreateEnvironmentObjectWithResponse call
func ParseCreateEnvironmentObjectResponse(rsp *http.Response) (*CreateEnvironmentObjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateEnvironmentObjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateEnvironmentObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteEnvironmentObjectResponse parses an HTTP response from a DeleteEnvironmentObjectWithResponse call
func ParseDeleteEnvironmentObjectResponse(rsp *http.Response) (*DeleteEnvironmentObjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteEnvironmentObjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetEnvironmentObjectResponse parses an HTTP response from a GetEnvironmentObjectWithResponse call
func ParseGetEnvironmentObjectResponse(rsp *http.Response) (*GetEnvironmentObjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEnvironmentObjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvironmentObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdateEnvironmentObjectResponse parses an HTTP response from a UpdateEnvironmentObjectWithResponse call
func ParseUpdateEnvironmentObjectResponse(rsp *http.Response) (*UpdateEnvironmentObjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateEnvironmentObjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvironmentObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseExcludeLinkingEnvironmentObjectResponse parses an HTTP response from a ExcludeLinkingEnvironmentObjectWithResponse call
func ParseExcludeLinkingEnvironmentObjectResponse(rsp *http.Response) (*ExcludeLinkingEnvironmentObjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExcludeLinkingEnvironmentObjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
