name: Import Script Tests

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  Authorize:
    environment: ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: true

  build:
    name: Build
    needs: Authorize
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.GOMODCACHE }}
            ~/.cache/go-build
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-
      - run: go mod download
      - name: Build import script
        run: go build -o import_script ./import/import_script.go

  test-import-script:
    name: Import Script Tests
    needs: build
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request_target'
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        terraform:
          - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.GOMODCACHE }}
            ~/.cache/go-build
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - name: Run import script tests
        env:
          RUN_IMPORT_SCRIPT_TEST: true
          HOSTED_ORGANIZATION_API_TOKEN: ${{ secrets.DEV_HOSTED_ORGANIZATION_API_TOKEN }}
          HOSTED_ORGANIZATION_ID: clx42kkcm01fo01o06agtmshg
        run: make test-import-script
